### ISSUE TITLE
Gradient boosting not working

### ISSUE THREAD

**Issue by dwkwvss** [automl/auto-sklearn#326] opened 2017-07-17 22:40 UTC
It seems that Gradient boosting doesn't fit or throws an error due to to the default value of max_leaf_nodes being None. It seems the code tries to use an int() function on this parameter even though the max_leaf_nodes is a Nonetype. Unless it was deliberately designed so that I specify this hyperparameter, (which would defeat the purpose of autosklearn) I am confused as to why this is occuring.

**Comment by dwkwvss** [comment] 2017-07-17 22:49
On second look it's strange because the default value isn't None but still ends up being that way..

**Comment by mfeurer** [comment] 2017-07-18 03:11
Hm, I cannot reproduce this issue. Do you have a logfile showing that gradient boosting fails? I also checked the code, and I think it is correct. The default values is `"None"`, which is a string. In the statement

                if self.max_leaf_nodes == "None":
                    self.max_leaf_nodes = None
                else:
                    self.max_leaf_nodes = int(self.max_leaf_nodes)

it is check whether the value of that hyperparameter is a string. If yes, it is converted to `None` of type None. I hope this clarifies this issue.

**Comment by dwkwvss** [comment] 2017-07-18 18:53
The error message happens when I use refit() and when I explicitly cross validate.


clf = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task=total_runtime,
        include_preprocessors=["no_preprocessing"],
        include_estimators = ["adaboost","gaussian_nb", "gradient_boosting",
                             "liblinear_svc", "libsvm_svc","random_forest",
                             "k_nearest_neighbors","decision_tree"])
    
    features=data_numeric.iloc[:,:(num_col-1)]
    labels=data_numeric.iloc[:,(num_col-1)]
    #Fit the autosklearnclassifier
    
    clf.fit(X=features.copy(), y=labels.copy(), metric = autosklearn.metrics.balanced_accuracy)
    
    kf = KFold(n_splits=10, shuffle=True)
    
    # cross validate over 10 folds
    for train, test in kf.split(data_numeric):
        train_features = data_numeric.iloc[train,:(num_col-1)]
        train_labels = data_numeric.iloc[train, (num_col-1)]
        test_features = data_numeric.iloc[test,:(num_col-1)]
        test_labels = data_numeric.iloc[test,(num_col-1)]
        
        clf.refit(train_features, train_labels)
        
        predictions = clf.predict(test_features)
        error += error_calc(test_labels, predictions)
   

The error message I receive is the following:

/home/hduser1/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/components/classification/gradient_boosting.py in fit(self, X, y, sample_weight, refit)
     34     def fit(self, X, y, sample_weight=None, refit=False):
     35         self.iterative_fit(X, y, n_iter=1, sample_weight=sample_weight,
---> 36                            refit=True)
     37         while not self.configuration_fully_fitted():
     38             self.iterative_fit(X, y, n_iter=1, sample_weight=sample_weight)

/home/hduser1/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/components/classification/gradient_boosting.py in iterative_fit(self, X, y, sample_weight, n_iter, refit)
     66                 self.max_leaf_nodes = None
     67             else:
---> 68                 self.max_leaf_nodes = int(self.max_leaf_nodes)
     69             self.verbose = int(self.verbose)
     70 

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by dwkwvss** [comment] 2017-07-18 18:55
it's also strange because when I run cv implicitly by setting the resampling strategy in the autosklearnclassifier function, I get 0 as in the cv_result_ for the gradient boosting classifier, which I assume means it didn't properly run either.

**Comment by mfeurer** [comment] 2017-07-20 15:29
This seems to be related to #250. Does this error happen if you use one of the examples or only on your dataset?

**Comment by dwkwvss** [comment] 2017-07-25 16:21
I've used it on my dataset. I checked by running on more than one dataset to confirm that this is not unique to the first dataset I used the function refit

**Comment by mfeurer** [comment] 2017-07-30 06:33
Okay, I found the bug, now I need to think about a solution. The issue is the multiple call to `refit`, which we didn't consider when writing the code. Therefore, we didn't test for it and it apparently fails. A temporary solution would be to pickle the automl object prior to calling `refit` and then unpickling it in every iteration. However, I'm not sure what you want to achieve with your cross-validation after the fit. I assume you trained already on the full data set. If you then do a CV on the same data, this will be overly optimistic, as the hyperparameters were optimized for some of the test sets. Please excuse the slow answering, I'm currently not at university and have only very limited time to take care of this project.

**Comment by Inexpugnable** [comment] 2017-10-10 13:46
I have tested to save as you suggest a pickle object of the fitted AutoSklearnClassifier object, but that doesn't seem to work because I obtain a kind of similar error when I try to load this pickle object at each iteration prior to calling the refit method on it.

```
Traceback (most recent call last):
  File "kfold_autosklearn_experiment.py", line 174, in <module>
    model.refit(X.copy(), y.copy())
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 50, in refit
    return self._automl.refit(X, y)
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 50, in refit
    return self._automl.refit(X, y)
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/automl.py", line 497, in refit
    model.fit(X.copy(), y.copy())
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/base.py", line 89, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/base.py", line 104, in fit_estimator
    self.steps[-1][-1].fit(X, y, **fit_params)
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/base.py", line 379, in fit
    return self.choice.fit(X, y, **kwargs)
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/classification/gradient_boosting.py", line 36, in fit
    refit=True)
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/classification/gradient_boosting.py", line 68, in iterative_fit
    self.max_leaf_nodes = int(self.max_leaf_nodes)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Exception ignored in: <bound method BackendContext.__del__ of <autosklearn.util.backend.BackendContext object at 0x7f82fd10ccf8>>
Traceback (most recent call last):
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/util/backend.py", line 74, in __del__
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/util/backend.py", line 83, in delete_directories
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/site-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/util/logging_.py", line 67, in warning
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/logging/__init__.py", line 1297, in warning
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/logging/__init__.py", line 1421, in _log
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/logging/__init__.py", line 1431, in handle
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/logging/__init__.py", line 1493, in callHandlers
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/logging/__init__.py", line 861, in handle
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/logging/__init__.py", line 1053, in emit
  File "/home/edouard/anaconda2/envs/py35/lib/python3.5/logging/__init__.py", line 1043, in _open
NameError: name 'open' is not defined
```

**Comment by Inexpugnable** [comment] 2017-10-20 12:02
An another error log related to this case:
```
  File "kfold_autosklearn_experiment.py", line 146, in <module>
    model.refit(X_array, y_array)
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/estimators.py", line 50, in refit
    return self._automl.refit(X, y)
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/estimators.py", line 50, in refit
    return self._automl.refit(X, y)
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/automl.py", line 506, in refit
    raise e
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/automl.py", line 497, in refit
    model.fit(X.copy(), y.copy())
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/pipeline/base.py", line 89, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/pipeline/base.py", line 104, in fit_estimator
    self.steps[-1][-1].fit(X, y, **fit_params)
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/pipeline/components/base.py", line 379, in fit
    return self.choice.fit(X, y, **kwargs)
  File "/user/rgazzott/home/anaconda3/envs/envy/lib/python3.6/site-packages/auto_sklearn-0.2.1-py3.6-linux-x86_64.egg/autosklearn/pipeline/components/classification/lda.py", line 34, in fit
    raise ValueError(self.shrinkage)
ValueError: None
```

Really weird because depending of the algorithms involved in the pipeline sometimes that works and sometimes that fails.

**Comment by mfeurer** [comment] 2017-10-20 14:46
Will be fixed in the upcoming release of Auto-sklearn.

**Closed by mfeurer** 2017-10-20 14:46 UTC
