### ISSUE TITLE
DataPreprocessor/FeaturePreprocessor option NoPreprocessing does not disable Balancing in 0.14.6

### ISSUE THREAD

**Issue by shabir1** [automl/auto-sklearn#1440] opened 2022-04-14 08:09 UTC
## NoPreprocessing is not working in 0.14.6 ##
I am setting NoPreprocessing in include param of AutoSklearnClassifier but it still run Balancing(random_state=1) as data_preprocessor. In the 0.14.2 version it was working as expected. When I downgrade the version to 0.14.2 then it again works.

```
AutoSklearnClassifier(ensemble_nbest=10, ensemble_size=10,
                      include={'classifier': ['adaboost', 'bernoulli_nb',
                                              'decision_tree', 'extra_trees',
                                              'gaussian_nb',
                                              'gradient_boosting',
                                              'k_nearest_neighbors', 'lda',
                                              'liblinear_svc', 'libsvm_svc',
                                              'mlp', 'multinomial_nb',
                                              'passive_aggressive', 'qda',
                                              'random_forest', 'sgd'],
                               'data_preprocessor': ['NoPreprocessing'],
                               'feature_preprocessor': ['no_preprocessing']},
                      initial_configurations_via_metalearning=0,
                      max_models_on_disc=10, memory_limit=4072,
                      time_left_for_this_task=120)
```
Result of show models (0.14.6):
```
{36: {'model_id': 36, 'rank': 1, 'cost': 0.06060606060606055, 'ensemble_weight': 0.4, 'data_preprocessor': <autosklearn.pipeline.components.data_preprocessing.DataPreprocessorChoice object at 0x7f125efc5100>, 'balancing': Balancing(random_state=1), 'feature_preprocessor': <autosklearn.pipeline.components.feature_preprocessing.FeaturePreprocessorChoice object at 0x7f125f0355b0>, 'classifier': <autosklearn.pipeline.components.classification.ClassifierChoice object at 0x7f125f035c40>, 'sklearn_classifier': KNeighborsClassifier(n_neighbors=2)}, 43: {'model_id': 43, 'rank': 2, 'cost': 0.06060606060606055, 'ensemble_weight': 0.6, 'data_preprocessor': <autosklearn.pipeline.components.data_preprocessing.DataPreprocessorChoice object at 0x7f125f035fa0>, 'balancing': Balancing(random_state=1, strategy='weighting'), 'feature_preprocessor': <autosklearn.pipeline.components.feature_preprocessing.FeaturePreprocessorChoice object at 0x7f1282c1d9a0>, 'classifier': <autosklearn.pipeline.components.classification.ClassifierChoice object at 0x7f125ef13b50>, 'sklearn_classifier': KNeighborsClassifier(n_neighbors=2)}}
```
Result of show models (0.14.2):
```
[(0.400000, SimpleClassificationPipeline({'balancing:strategy': 'weighting', 'classifier:__choice__': 'k_nearest_neighbors', 'data_preprocessor:__choice__': 'NoPreprocessing', 'feature_preprocessor:__choice__': 'no_preprocessing', 'classifier:k_nearest_neighbors:n_neighbors': 1, 'classifier:k_nearest_neighbors:p': 2, 'classifier:k_nearest_neighbors:weights': 'distance'},\ndataset_properties={\n  'task': 1,\n  'sparse': False,\n  'multilabel': False,\n  'multiclass': False,\n  'target_type': 'classification',\n  'signed': False})),\n(0.200000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'classifier:__choice__': 'k_nearest_neighbors', 'data_preprocessor:__choice__': 'NoPreprocessing', 'feature_preprocessor:__choice__': 'no_preprocessing', 'classifier:k_nearest_neighbors:n_neighbors': 1, 'classifier:k_nearest_neighbors:p': 2, 'classifier:k_nearest_neighbors:weights': 'distance'},\ndataset_properties={\n  'task': 1,\n  'sparse': False,\n  'multilabel': False,\n  'multiclass': False,\n  'target_type': 'classification',\n  'signed': False})),\n(0.200000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'classifier:__choice__': 'k_nearest_neighbors', 'data_preprocessor:__choice__': 'NoPreprocessing', 'feature_preprocessor:__choice__': 'no_preprocessing', 'classifier:k_nearest_neighbors:n_neighbors': 1, 'classifier:k_nearest_neighbors:p': 2, 'classifier:k_nearest_neighbors:weights': 'uniform'},\ndataset_properties={\n  'task': 1,\n  'sparse': False,\n  'multilabel': False,\n  'multiclass': False,\n  'target_type': 'classification',\n  'signed': False})),\n(0.200000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'classifier:__choice__': 'k_nearest_neighbors', 'data_preprocessor:__choice__': 'NoPreprocessing', 'feature_preprocessor:__choice__': 'no_preprocessing', 'classifier:k_nearest_neighbors:n_neighbors': 3, 'classifier:k_nearest_neighbors:p': 2, 'classifier:k_nearest_neighbors:weights': 'distance'},\ndataset_properties={\n  'task': 1,\n  'sparse': False,\n  'multilabel': False,\n  'multiclass': False,\n  'target_type': 'classification',\n  'signed': False})),\n]
```
Every thing is same dataset, etc only version diff

**Comment by eddiebergman** [comment] 2022-04-14 09:11
Hi again @shabir1,

Please see this Issue:
* https://github.com/automl/auto-sklearn/issues/1431

Yes there are issues that remain here, we unfortunately don't have the manpower to fix all problems and keep up to speed with other automl frameworks. If you feel like taking a dive into the code, a PR that fixes these things would be much appreciated.

Best,
Eddie

**Comment by shabir1** [comment] 2022-04-18 05:32
@eddiebergman 
I tried to use balancing in include/exclude but it throws the error
```
AutoSklearnClassifier(ensemble_nbest=10, ensemble_size=10,
                      include={'balancing': 'none',
                               'classifier': [
                                              'decision_tree', 'extra_trees',
                                              'random_forest', 'sgd'],
                               'data_preprocessor': ['NoPreprocessing'],
                               'feature_preprocessor': ['no_preprocessing']},
                      initial_configurations_via_metalearning=0,
                      max_models_on_disc=10, memory_limit=4072,
                      time_left_for_this_task=120)
```
Error:
ValueError: The provided key 'balancing' in the 'include' argument is not valid. The only supported keys for this task are ['data_preprocessor', 'feature_preprocessor', 'classifier']
```
auto-sklearn==0.14.6

How can I disable balancing?

**Comment by eddiebergman** [comment] 2022-04-18 11:29
Hi @shabir1,

Please read the issue I linked in full, it's not possible:
* https://github.com/automl/auto-sklearn/issues/1431

Best,
Eddie

**Comment by eddiebergman** [comment] 2022-04-24 13:36
Closing as the issue is related to the one linked above

**Closed by eddiebergman** 2022-04-24 13:36 UTC
Labels: bug, duplicate
