### ISSUE TITLE
Calling automl.leaderboard() cause error

### ISSUE THREAD

**Issue by asmgx** [automl/auto-sklearn#1430] opened 2022-03-25 00:49 UTC
when I call `print(automl.leaderboard())`

after fitting an autosklearn model

but i get this error

```

>>> print(automl.leaderboard())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/am/.local/lib/python3.7/site-packages/autosklearn/estimators.py", line 841, in leaderboard
    model_runs[model_id]['ensemble_weight'] = weight

```

how to fix this?

note : Autosklearn version is 0.14.6

```

>>> autosklearn.__version__
'0.14.6'


```

**Comment by eddiebergman** [comment] 2022-03-25 11:16
Hi @asmgx,

I'm sorry, this can occasionally happen. If you can afford to, your best bet is to just rerun autosklearn and give it a different `seed` when constructing it. Alternatively you can get much of the same information out of `automl.show_models()`.

The reason for this is a weird mismatch that occurs between id's which shouldn't happen, but does.

Sorry that it is the best I can offer. It's hard to reproduce which makes it hard to fix but if the issue happens again, then please send on the code and data (if you can) that makes this occur.

Best,
Eddie

**Comment by eddiebergman** [comment] 2022-03-25 15:27
Hi @asmgx, I put in what I hope should be a small fix that doesn't solve underlying issue but at least prevents raising an error and providing back the information it can. See #1432

**Comment by eddiebergman** [comment] 2022-03-28 17:18
Should be fixed now :) It might miss one model on the odd time that happens but it at least won't crash now

**Closed** 2022-03-28 17:18 UTC
Labels: bug
