### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by iirekm** [automl/auto-sklearn#868] opened 2020-05-31 14:36 UTC
auto-sklearn was exactly I was looking for, unfortunately fails even on example from docs:

```python
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

import autosklearn.regression

def main():
    X, y = sklearn.datasets.load_boston(return_X_y=True)
    feature_types = (['numerical'] * 3) + ['categorical'] + (['numerical'] * 9)
    X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)
    automl = autosklearn.regression.AutoSklearnRegressor(
        time_left_for_this_task=120,
        per_run_time_limit=30,
        tmp_folder='/tmp/autosklearn_regression_example_tmp',
        output_folder='/tmp/autosklearn_regression_example_out',
    )
    automl.fit(X_train, y_train, dataset_name='boston',
               feat_type=feature_types)

    print(automl.show_models())
    predictions = automl.predict(X_test)
    print("R2 score:", sklearn.metrics.r2_score(y_test, predictions))


if __name__ == '__main__':
    main()
```

```
/home/.../.venv/bin/python3.8 /home/.../workspace/varia-private/qtrading/asl.py
/home/.../.venv/lib/python3.8/site-packages/pyparsing.py:3174: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
[WARNING] [2020-05-31 16:35:21,635:AutoMLSMBO(1)::boston] Could not find meta-data directory /home/.../.venv/lib/python3.8/site-packages/autosklearn/metalearning/files/r2_regression_dense

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

OS: Ubuntu 20
Python: 3.8.2

**Comment by mfeurer** [comment] 2020-06-09 09:52
This is a duplicate of https://github.com/automl/auto-sklearn/issues/856. The underlying issue is that a dependency (pyrfr) is compiled with SWIG4 (which is the Ubuntu 20.04 default), but is only compatible with SWIG3.

**Closed by mfeurer** 2020-06-09 09:52 UTC
