### ISSUE TITLE
trying to launch, but does not seem to work'

### ISSUE THREAD

**Issue by turbogeek** [automl/auto-sklearn#598] opened 2018-12-15 22:37 UTC
trying to launch with
docker run -it -v $PWD:/opt/nb -p 8888:8888 mfeurer/auto-sklearn /bin/bash -c "mkdir -p /opt/nb && jupyter notebook --notebook-dir=/opt/nb --ip='0.0.0.0' --port=8888 --no-browser --allow-root"

works to launch but get this error in python from the jypter console:
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-12-4bca471f042a>", line 2, in <module>
    import autosklearn.classification

**Comment by mfeurer** [comment] 2018-12-17 09:32
It seems that your error message is truncated.

**Comment by turbogeek** [comment] 2018-12-17 18:30
> It seems that your error message is truncated.

That was it, the issue is that is failing to even import anything from autosklearn. I am able to connect to the jupyter notebook in the image, it just does not seem to have any path within the container to make it work. Am I missing something about how I am supposed to launch the notebook?

**Comment by mfeurer** [comment] 2018-12-19 10:16
I must admit that I do not know how to make this work because I never used it myself. I think this was contributed by @felixleungsc, maybe he can help?

**Comment by felixleungsc** [comment] 2018-12-20 12:40
Hi Daniel, I ran the same docker run command as you did, but couldn't reproduce the error you reported.

I assume after you launched the jupyter notebook, you ran `import autosklearn.classification`. When I did that, I got no error message. In fact, the auto-sklearn example from https://automl.github.io/auto-sklearn/master/ worked just fine for me.

Could you @turbogeek try running only `import autosklearn.classification` and see if you still get the same error message?

**Comment by felixleungsc** [comment] 2018-12-29 11:33
@turbogeek Do you still get the same error message? If not, could this issue be closed now? Thanks.

**Comment by mfeurer** [comment] 2020-07-23 14:42
Closing this as the issue is quite old and we just changed our docker workflow to build images via github actions: https://github.com/automl/auto-sklearn/packages

**Closed by mfeurer** 2020-07-23 14:42 UTC
