### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by NothingLZ** [automl/auto-sklearn#644] opened 2019-02-28 12:30 UTC
![image](https://user-images.githubusercontent.com/12367891/53566619-a4a6b500-3b97-11e9-971e-9a944fb60b66.png)

**Comment by mfeurer** [comment] 2019-03-04 10:22
Thanks for reporting this, but it appears to be a duplicate of #600, so I'm closing this. Please reopen if that's not the case.

**Closed by mfeurer** 2019-03-04 10:22 UTC
