### ISSUE TITLE
PyPI version lacks requirements on lockfile and smac

### ISSUE THREAD

**Issue by fnielsen** [automl/auto-sklearn#206] opened 2016-12-13 16:27 UTC
While the current requirements.txt file has "lockfile" and "smac==0.2.1" the current version on PyPI (0.1.1) errs on installation because these requirements do not get installed.

**Comment by mfeurer** [comment] 2016-12-15 10:35
In order to track down this issue I need some more information. Could you please provide the following information:

* the python version, and whether this python is installed in an AnaConda or virtualenv environment
* your operating system
* the commands you used to install auto-sklearn, preferably with the output.

**Comment by fnielsen** [comment] 2016-12-15 15:23
Python 3.5.2 on Ubuntu 16.04 LTS installing with pip3 (sudo pip3 install auto-sklearn)

**Comment by mfeurer** [comment] 2016-12-16 09:24
Did you install the dependencies before running `sudo pip3 install auto-sklearn`? If not, please follow the installation guidelines [here](https://automl.github.io/auto-sklearn/stable/#installation).

**Comment by fnielsen** [comment] 2016-12-16 10:27
I have already installed it by installing the dependencies manually. I was wondering why the requirements are not installed automatically. I was expecting that a PyPI version would always install dependencies automatically. Is the manual configuration because some of the dependencies are fixed versions? Doesn't the current GitHub master version install automatically?

**Comment by mfeurer** [comment] 2016-12-16 15:29
On a call to `python setup.py install`, the installation script tries to import the setup files of all dependencies. These can have dependencies as well, and I don't know how one can ensure that they get installed before that. Installing them with `pip install -r requirements.txt` or the method layed out in the setup file works nicely. If you know of a cleaner solution, I'd be happy to change the installation procedure (please reopen the issue then).

**Comment by fnielsen** [comment] 2016-12-20 12:58
Here is an example of problem with pip installation: 

```
$ sudo -H pip3 install auto-sklearn
Collecting auto-sklearn
  Using cached auto-sklearn-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fzrj854l/auto-sklearn/setup.py", line 2, in <module>
        import autosklearn
      File "/tmp/pip-build-fzrj854l/auto-sklearn/autosklearn/__init__.py", line 2, in <module>
        from autosklearn.util import dependencies
      File "/tmp/pip-build-fzrj854l/auto-sklearn/autosklearn/util/__init__.py", line 4, in <module>
        from .common import *
      File "/tmp/pip-build-fzrj854l/auto-sklearn/autosklearn/util/common.py", line 4, in <module>
        from sklearn.externals import six
    ImportError: No module named 'sklearn'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fzrj854l/auto-sklearn/
```

**Comment by fnielsen** [comment] 2016-12-20 14:35
I have stackoverflowed the issue here https://stackoverflow.com/questions/41244479/getting-importerror-no-module-named-sklearn-when-installing-auto-sklearn

**Comment by mfeurer** [comment] 2016-12-20 14:41
Sorry for closing this too early, I assumed you just want to know how to install auto-sklearn. If we figure out how to solve this installation issue, it would be great.

**Comment by fnielsen** [comment] 2016-12-20 15:21
I finally spotted the issue: https://github.com/automl/auto-sklearn/blob/master/setup.py#L2 You are importing autosklearn in `setup.py` before it is installed.

**Comment by jtyberg** [comment] 2017-01-24 21:20
@mfeurer I got stuck trying to install, so I submitted a PR to fix `setup.py`.

**Comment by mfeurer** [comment] 2017-01-25 08:25
@fnielsen thanks for sorting this out. This appears now to be a duplicate of #198, so I'm closing it for now. Please reopen this issue if it is not sorted out on the development branch now or later this week with a new bugfix release.

**Closed by mfeurer** 2017-01-25 08:25 UTC

**Comment by fnielsen** [comment] 2017-01-25 09:40
Yes, this appear as a duplicate of #198. Thanks.
