### ISSUE TITLE
Intel MKL FATAL ERROR: cannot load libmkl_vml_avx.so or libmkl_vml_def.so.

### ISSUE THREAD

**Issue by kaiweiang** [automl/auto-sklearn#530] opened 2018-08-18 11:37 UTC
Hi,

When I was using autosklearn on a multiclass dataset, I encountered the following error

```
  File "modeling.py", line 26, in main
    alg.fit()
  File "/var/www/html/MC_PY/mc_modules/mc_automl/base.py", line 455, in fit
    self.train()
  File "/var/www/html/MC_PY/mc_modules/mc_automl/categorization.py", line 28, in train
    self.automl.refit(self.X_train.copy(), self.y_train.copy())
  File "/root/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 329, in refit
    self._automl.refit(X, y)
  File "/root/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 878, in refit
    return super().refit(X, y)
  File "/root/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 497, in refit
    raise ValueError("Refit can only be called if 'ensemble_size != 0'")
ValueError: Refit can only be called if 'ensemble_size != 0'

```
This was the output I printed when autosklearn was running, it clearly stated the `ensemble_size=50`
```
AutoSklearnClassifier(delete_output_folder_after_terminate=True,
           delete_tmp_folder_after_terminate=True,
           disable_evaluator_output=False, ensemble_nbest=50,
           ensemble_size=50, exclude_estimators=None,
           exclude_preprocessors=None, get_smac_object_callback=None,
           include_estimators=['random_forest', 'gradient_boosting', 'adaboost', 'extra_trees'],
           include_preprocessors=None,
           initial_configurations_via_metalearning=25,
           ml_memory_limit=3072, output_folder=None, per_run_time_limit=60,
           resampling_strategy='holdout',
           resampling_strategy_arguments={'train_size': 0.7}, seed=1,
           shared_mode=False, smac_scenario_args=None,
           time_left_for_this_task=180, tmp_folder=None)
Autosklearn fitting started
/root/anaconda3/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
[WARNING] [2018-08-18 19:25:03,697:EnsembleBuilder(1):37e6b330c019eb05254e37940cf1618d] No models better than random - using Dummy Classifier!
Intel MKL FATAL ERROR: cannot load libmkl_vml_avx.so or libmkl_vml_def.so.
/root/anaconda3/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
/root/anaconda3/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py:197: RuntimeWarning: Mean of empty slice
  Y_train_pred = np.nanmean(Y_train_pred_full, axis=0)
[WARNING] [2018-08-18 19:27:50,025:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2018-08-18 19:27:50,025:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
```

Somehow, when I was using another multiclass dataset, the autosklearn managed to run without any issue when the optimization metric was set to `f1_micro` or `f1_macro`, but the above error did happen when the metric was set to `log_loss`.

Any idea what happened?
I'm guessing it was caused by the error ```Intel MKL FATAL ERROR: cannot load libmkl_vml_avx.so or libmkl_vml_def.so.```, but this error didn't show up during binary classification.

**Comment by mfeurer** [comment] 2018-08-20 15:29
Is it possible that you reproduce this with a dummy dataset and share the code? Also, please check if #500 is the cause of this.

**Comment by mfeurer** [comment] 2018-08-20 15:31
Regarding the Intel MKL error: I don't know how to solve these and usually rebuild my conda environment to get rid of them. The reason why you see them only during multiclass optimization is most likely the fact that some algorithms are only applicable to multiclass and not binary classification.

**Comment by kaiweiang** [comment] 2018-08-21 02:17
I tested on mushroom dataset with the `habitat` column as the response variable and it worked fine.

The dataset that caused this error was the train.csv from [Prudential Life Insurance Assessment](https://www.kaggle.com/c/prudential-life-insurance-assessment/data)

**Comment by kaiweiang** [comment] 2018-08-31 09:37
@mfeurer 
Regarding the Intel MKL error, I solved it by adding the two files to the `LD_PRELOAD` environment path,
`LD_PRELOAD=$LD_PRELOAD:/root/anaconda3/lib/libmkl_vml_avx.so:/root/anaconda3/lib/libmkl_vml_def.so
`

**Comment by mfeurer** [comment] 2018-11-12 11:47
This is not directly related to Auto-sklearn - closing.

**Closed by mfeurer** 2018-11-12 11:47 UTC
