### ISSUE TITLE
Evaluating the ensemble suggested by auto-sklearn

### ISSUE THREAD

**Issue by mcachada** [automl/auto-sklearn#260] opened 2017-04-07 10:47 UTC
Hi, first of all, congratulations to all for the efforts on making auto-sklearn a reality.

It is my understanding that the grid_scores_ and cv_results_ attributes only lists scores for every individual model. I would like, however, to evaluate the merit of the ensemble recommended by auto-sklearn. I know I can use a simple holdout method but I would prefer something more robust like cross validation.

So, my idea is basically the following: 

1) initialise an "automl" object
2) fit on 100% data
3) using a scikit-learn cross validation iterator, perform CV-10 fold with refit

I adapted your digits example to the above procedure as follows:

```
import sklearn.cross_validation as scv
import sklearn.datasets
import sklearn.metrics
import autosklearn.classification
import numpy as np

#Global variables
time_budget = 300
per_run_proportion = 0.1

if __name__ == '__main__':

    #import data
    digits = sklearn.datasets.load_digits()
    X = digits.data
    y = digits.target
    
    #define automl object
    automl = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task = time_budget, per_run_time_limit = \
            int(time_budget*per_run_proportion),
        tmp_folder='/tmp/autoslearn_holdout_example_tmp',
        output_folder='/tmp/autosklearn_holdout_example_out',
        delete_tmp_folder_after_terminate=False,
        resampling_strategy='cv',
        resampling_strategy_arguments={'folds': 5}, 
        disable_evaluator_output=False)
    
    #find ensemble of estimators
    automl.fit(X.copy(), y.copy(), dataset_name='digits')

    #CROSS VALIDATION 10-FOLD to evaluate ensemble
    #define cv iterator (force stratified)
    cv_iter = scv.StratifiedKFold(y, n_folds = 10, shuffle = True, random_state = 123)
    
    #estimate accuracy per fold
    print("Cross validation 10-fold")
    acc_idx = 0
    acc_array = np.empty(10)
    for train, test in cv_iter:
        X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]  
        automl.refit(X_train, y_train)
        predictions = automl.predict(X_test)
        acc_score = sklearn.metrics.accuracy_score(y_test, predictions)
        print("Accuracy score", acc_score)
        acc_array[acc_idx] = acc_score
        acc_idx += 1
    
    #get mean accuracy
    mean_acc = np.mean(acc_array)

```

So, my questions are:

1) Does the above procedure seem correct? How serious would a potential problem of data leakage be, taking into consideration that the folds on "my" cross validation are different from the ones used by autosklearn itself on its internal evaluation? Do you have any other suggestions to evaluate the ensemble besides using a holdout method?

2) When I run the code above I get a "ValueError: X has 58 features per sample; expecting 57". How can I solve this?

**Comment by mfeurer** [comment] 2017-04-11 08:18
Hi,
I do not know any other way of evaluating the final ensemble except for using a holdout set. A different way would be to evaluate auto-sklearn using nested cross-validation. You would then fit auto-sklearn in each CV fold. This will not explain the performance of a single ensemble, but show you the performance you can expect when running auto-sklearn.

And to answer your questions:
1. I think the data leakage can be a problem and you should not use the mentioned method to compare auto-sklearn to different procedures. The models you fit in your post-hoc CV will have seen parts of the data already during the hyperparameter optimization, which will make them fit the data unrealistically good.
2. I cannot reproduce the ValueError here, but auto-sklearn is allowed to modify the data you pass. Passing only copies to `automl.refit` and `automl.predict` could alleviate the problem.

**Comment by mcachada** [comment] 2017-04-11 09:54
Hello, thank you for your answer. 

I understand your suggestion of switching my purpose from evaluating the recommendation to evaluating the "recommendation system" itself. It sure seems the cleanest way of doing it. Main drawback of this solution is the time it potentially may take. Still, it is something I will consider. Thanks again for the feedback.

Regarding my second question, I tried your suggestion and still no luck... Even so, since the most relevant question was answered, should I close the issue?

Best regards,
Miguel

**Comment by mfeurer** [comment] 2017-04-11 12:10
Could you please post the full traceback?

**Comment by mcachada** [comment] 2017-04-11 12:54
Sure, find it below. It occurs on the second fold of "my" CV.

-------------------------------------------------------------
Cross validation 10-fold
Accuracy score 0.994594594595
Traceback (most recent call last):

  File "<ipython-input-2-3d245ebd85f4>", line 43, in <module>
    predictions = automl.predict(X_test.copy())

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/autosklearn/estimators.py", line 373, in predict
    return super(AutoSklearnClassifier, self).predict(X)

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/autosklearn/estimators.py", line 66, in predict
    return self._automl.predict(X)

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/autosklearn/estimators.py", line 532, in predict
    predicted_probabilities = self._automl.predict(X)

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/autosklearn/automl.py", line 505, in predict
    prediction = model.predict_proba(X_)

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 127, in predict_proba
    return self.steps[-1][-1].predict_proba(Xt)

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/autosklearn/pipeline/components/classification/__init__.py", line 126, in predict_proba
    return self.choice.predict_proba(X)

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/autosklearn/pipeline/components/classification/sgd.py", line 99, in predict_proba
    df = self.estimator.decision_function(X)

  File "/home/mcachada/anaconda3/envs/autosklearn/lib/python3.5/site-packages/sklearn/linear_model/base.py", line 249, in decision_function
    % (X.shape[1], n_features))

ValueError: X has 58 features per sample; expecting 57

**Comment by Motorrat** [comment] 2017-04-20 15:55
I have the same problem with the failing prediction after a recent fresh installation of the full stack (fresh Ubuntu 16.04, Anaconda, auto-sklearn) 
" Expected input with 10 features, got 8 instead"
to isolate the issue I have even put a copy of the same data in both refit and predict methods:
```
c.refit(X.copy().values, y)
y_pred = c.predict(X.copy().values)
```

**Comment by mfeurer** [comment] 2017-04-26 06:53
Okay, the following code snippet allows to replay the error after a failed call to `refit()`:
```
import sklearn.cross_validation as scv
import sklearn.datasets
import sklearn.metrics
from autosklearn.classification import AutoSklearnClassifier
import logging

digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target

cv_iter = scv.StratifiedKFold(y, n_folds=10, shuffle=True, random_state=123)

auto = AutoSklearnClassifier(delete_tmp_folder_after_terminate=False,
                             tmp_folder='/tmp/autoslearn_holdout_example_tmp')
auto._automl = auto.build_automl()
auto._automl._automl._logger = logging.getLogger()

acc_idx = 0
for i, (train, test) in enumerate(cv_iter):
    print(i)
    X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]
    auto.refit(X_train, y_train)
    predictions = auto.predict(X_test)
```
Now I only need to find the actual bug...

**Comment by mfeurer** [comment] 2017-04-26 07:39
Okay, the issue is that (at least) the fit method SGDClassifier is not idempotent. Here's a quote from the sklearn manual:

    The last-mentioned attributes are expected to be overridden when you call fit a second time without taking any previous value into account: fit should be idempotent.

In particular, a second call to fit (if the object is still the same), will return the already fitted classifier instead of retraining on the new training data.

**Comment by mfeurer** [comment] 2017-04-26 14:13
I just merged a fix to the development branch, will be there in the next release.

**Closed by mfeurer** 2017-04-26 14:13 UTC
