### ISSUE TITLE
Can't find meta-data directory

### ISSUE THREAD

**Issue by bakirillov** [automl/auto-sklearn#745] opened 2019-11-15 12:13 UTC
Hello!

The following code
automl = autosklearn.regression.AutoSklearnRegressor(
    tmp_folder='./tmp/autosklearn_regression_example_tmp',
    output_folder='./tmp/autosklearn_regression_example_out',
)
automl.fit(
    X=train_internals, 
    y=train_targets, 
    X_test=val_internals, y_test = val_targets
)

fails with
[WARNING] [2019-11-15 15:11:23,832:AutoMLSMBO(1)::3d48df5eff35a407ca25d900e33a43ca] Could not find meta-data directory /home/bakirillov/anaconda3/envs/lapki/lib/python3.7/site-packages/autosklearn/metalearning/files/r2_regression_dense

What is going on? How can I fix it?

**Comment by mfeurer** [comment] 2020-01-07 16:00
Unfortunately, we currently don't have meta-data for regression. I hope this I'll have the time to generate it for the next major release.

I'm closing this for now as it is a duplicate of #280

**Closed by mfeurer** 2020-01-07 16:00 UTC
