### ISSUE TITLE
support for sklearn 0.18.1

### ISSUE THREAD

**Issue by jankrnavek** [automl/auto-sklearn#251] opened 2017-03-07 19:00 UTC
Hello,
can you update package in order to use sklearn in version  0.18.1?
I appreciate your work ant thank you in advance.
Hanz

**Comment by marcosgabbardo** [comment] 2017-03-11 22:14
Support for Mac OS  will be good too...

**Comment by mfeurer** [comment] 2017-03-24 15:22
This is a duplicate of #186. I hope that we get to this in the near future.

**Closed by mfeurer** 2017-03-24 15:22 UTC
