### ISSUE TITLE
[Question] Different measurements per sample pre-processing

### ISSUE THREAD

**Issue by fferroni** [automl/auto-sklearn#497] opened 2018-06-19 07:43 UTC
Hello,

My classification dataset has a different number of features per example. This is because I get a different number of measurements per sample which I am trying to classify, like trying to classify a sentence, or classifying a sequence, or an unordered set of points.

I am wondering whether Auto-Sklearn has the ability to explore the featurizing step as well as the classifier/ensembles. For example, exploring whether taking min, max, standard deviation, count and other combinations of features on the measurements of a single sample would lead to a better classification.

Thanks!

**Comment by mfeurer** [comment] 2018-06-19 08:41
This is not possible at the moment. I'm closing this now because it is a duplicate of #379.

**Closed by mfeurer** 2018-06-19 08:41 UTC
