### ISSUE TITLE
run_wrapper() got an unexpected keyword argument 'pure'

### ISSUE THREAD

**Issue by piproul** [automl/auto-sklearn#1406] opened 2022-02-17 21:46 UTC
While running a fitting on a classifier (*output[0]* with data *output[1]* to *output[4]*), I get the following error; I think it's packages issue;

   > output[0].fit(output[1], output[2], output[3], output[4])
   > File "/usr/local/lib/python3.8/dist-packages/autosklearn/estimators.py", line 1045, in fit
     super().fit(
   > File "/usr/local/lib/python3.8/dist-packages/autosklearn/estimators.py", line 375, in fit
     self.automl_.fit(load_models=self.load_models, **kwargs)
   > File "/usr/local/lib/python3.8/dist-packages/autosklearn/automl.py", line 2056, in fit
     return super().fit(
   > File "/usr/local/lib/python3.8/dist-packages/autosklearn/automl.py", line 931, in fit
     _proc_smac.run_smbo()
   > File "/usr/local/lib/python3.8/dist-packages/autosklearn/smbo.py", line 498, in run_smbo
     smac.optimize()
   > File "/usr/local/lib/python3.8/dist-packages/smac/facade/smac_ac_facade.py", line 720, in optimize
     incumbent = self.solver.run()
   > File "/usr/local/lib/python3.8/dist-packages/smac/optimizer/smbo.py", line 287, in run
     self.tae_runner.submit_run(run_info=run_info)
   > File "/usr/local/lib/python3.8/dist-packages/smac/tae/dask_runner.py", line 166, in submit_run
     self.client.submit(
   > File "/usr/local/lib/python3.8/dist-packages/autosklearn/util/single_thread_client.py", line 59, in submit
     return DummyFuture(func(*args, **kwargs))
 > **TypeError: run_wrapper() got an unexpected keyword argument 'pure'**

It seems like it's an error with Dask. Here are the installed packages on ubuntu 18.04

pandas==1.3.0
scikit-learn==0.24
dask==2021.12.0
auto-sklearn==0.14.5    #AutoML
tensorflow==2.8.0

I've tried all versions of dask from 2021.12.0 to 2022.02.0 (Current) and nothing seems to work. Downgrading to auto-sklearn 0.14.4 and lower didn't solve the problem.

**Comment by koureasstavros** [comment] 2022-02-18 09:01
Same here, running in Google Colab with default libraries and installing the latest AutoSKLearn produces TypeError: run_wrapper() got an unexpected keyword argument 'pure'. Also tried downgraded versions and other problems are occurring now.

**Comment by eddiebergman** [comment] 2022-02-18 10:08
Hey, thanks for reporting this issue! I can't reproduce it with a fresh install and default arguments so I'll need to ask a few more questions to try reproduce it.

* What arguments are you initializing the AutoML objects with? Are you using your own Dask cluster?
* Your error log seemed to indicate python 3.8, just want to clarify this?
* Is this a deterministic error, i.e. it will happen every time?
* Could you do a clean install of auto-sklearn and see if this gets reproduced? For example, you listed tensorflow which we don't use. It would handy to get a full `pip list` so I can compare it.

**Comment by eddiebergman** [comment] 2022-02-18 10:16
The easiest solution for now is to downgrade SMAC to 1.1.1 as there was a new release yesterday and this was causing the issue. I'll report back once I know more :)

**Comment by eddiebergman** [comment] 2022-02-18 11:00
This is fixed in #1407 and will be released as version `0.14.6` soon.

**Closed** 2022-02-18 11:05 UTC

**Comment by eddiebergman** [comment] 2022-02-18 11:12
Version `0.14.6` has been released with the hotfix. Apologies for the inconvenience.

For anyone who faced this issue, installing the latest version of autosklearn should now fix the problem. Please comment if this has not fixed the issue
