### ISSUE TITLE
Error in Example/pyrfr compilation error

### ISSUE THREAD

**Issue by arita297** [automl/auto-sklearn#119] opened 2016-08-26 19:01 UTC
On Ubuntu, when loading the package,we have the message:

ImportError: /home/linux1/anaconda2/lib/python2.7/site-packages/pyrfr/regression.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE

Any idea ?

**Comment by mfeurer** [comment] 2016-08-29 13:27
Sorry, I do not know how this can happen. @sfalkner could you please take this over?

**Comment by sfalkner** [comment] 2016-08-29 17:42
This usually happens when the gcc version used to build pyrfr ( our own random forest implementation in C++) and the one used to build the python executable are different, or something similar that breaks proper linking (probably NumPy, the only real dependency of pyrfr).
I am no anaconda expert, but I assume that some gcc/library path got messed up during the installation of auto-sklearn. The anaconda FAQ has this entry, but I it doesn't mean anything to me:

https://docs.continuum.io/anaconda/faq#how-do-you-handle-linking-problems-when-python-extensions-are-compiled-with-gcc

There might be some question on StackOverflow with more detail.
I am more than happy to help out as much as possible, but I have no Anaconda experience, and I am not eager to change that.

Best, Stefan

**Comment by arita297** [comment] 2016-08-29 18:04
Hi,

Can you describe in details the machine on which:
     1) You have compiled.
     2) Different people are using now ?

It would help if one can match it.

**Comment by sfalkner** [comment] 2016-08-29 19:31
The package compiles fine on a current Gentoo and Arch Linux. It also work fine on Ubuntu 14.04 LTS. I personally use it only with system packages, but my colleagues usually install it in virtual environments. If I remember correctly, the package will not compile under MacOS, as some C++11 parts don't work with homebrew.
The package also compiles for both Python 2 and 3, although I only develop and test on 3.
These 'undefined symbol' errors always hint at problems with some python libraries during compiling. For example, if you compile it for Python 2 and try to import it in 3 a similar error occurs. In your case, the problem stems for the fact that all your anaconda libs come pre-compiled with some unknown gcc version, and pyrfr is compiled with you system's gcc. I am sure someone on the internet must have tried installing a package that needs to be linked agains anaconda packages, here NumPy.

**Comment by arita297** [comment] 2016-08-29 19:41
Hi,

In order to make constructive,

1) To summarize, what is the compilation framework ?
GCC version ?
Linux version ?
Python version ?  (+ gcc compiler version ?°
Dependencies version of python package (numpy ?)


2) What is the framework, where it is currently used
GCC version ?
Linux version number ?
Python version ?  (+ gcc compiler version ) ?

**Comment by sfalkner** [comment] 2016-08-29 19:45
The package compiles on your machine when you install it; it is not precompiled!

**Comment by arita297** [comment] 2016-08-29 20:33
Hello,

So, would it be possible to indicate clearly and precisely:
in order to make constructive,

1) the framework where you have successfully compiled this version of 
auto-sklearn ?
GCC version ?
Linux version ?
Python version ?  (+ gcc compiler version )
Dependencies version of python package (numpy ?)



2) The framework when this package is currently being used ( after 
compilation on other framework )
GCC version ?
Linux version ?
Python version ?  (+ gcc compiler version )

**Comment by sfalkner** [comment] 2016-08-29 21:09
First of all, the problem is not really auto-sklearn related, but only to the dependency pyrfr, so the auto-sklearn version doesn't really matter.

GCC versions sucessfully used: 4.8, 4.9 and 6.1
Linux versions: Gentoo, Arch Linux, Ubuntu 14.04 LTS and I think 16.04
Python versions: Python 2.7, 3.4 and 3.5
Numpy versions: 1.9.2, 1.11.1

But I want to stress again that the actual versions don't really matter. What causes your problem is anaconda related. If you have numpy installed on that machine, you could install pyrfr with the system's python most likely without any problems.
If you continue to have problems, we should move this issue over to pyrfr and fix it there.

**Comment by mfeurer** [comment] 2016-08-30 06:56
You can also have a look at our travis-ci setup. It successfully uses miniconda to install the pyrfr (although the numpy version is installed via pip). You can also have a look at the travis-ci setup form the [SMAC optimizer](https://github.com/automl/SMAC3) which uses numpy and scipy from miniconda.

Besides that, my machine runs Ubuntu 14.04 LTS with:

* gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
* Python 3.4.3 (default, Oct 14 2015, 20:28:29), [GCC 4.8.4] on linux

Besides that, I'm not using anaconda but the virtualenv package and do not add any directory to any PATH variable in my .bashrc.

**Comment by suny16907** [comment] 2016-09-23 03:41
do you fixed the problem, i meet the same question like you ,if you know, can you tell me? thanks very much

**Comment by mfeurer** [comment] 2016-10-17 11:44
I'm closing this since there was no new post during the last few weeks. Please reopen this issue if you think it's not yet solved.

**Closed by mfeurer** 2016-10-17 11:44 UTC
