### ISSUE TITLE
Could not find meta-data directory warning

### ISSUE THREAD

**Issue by mitar** [automl/auto-sklearn#294] opened 2017-05-29 20:50 UTC
I am getting the following warning when running a regression on sklearn digits dataset:

```
[WARNING] [2017-05-29 20:07:13,905:AutoMLSMBO(1)::d74860caaa557f473ce23908ff7ba369] Could not find meta-data directory /usr/local/lib/python3.5/dist-packages/autosklearn/metalearning/files/r2_regression_dense
```

**Comment by mfeurer** [comment] 2017-05-30 06:34
This is a duplicate of #280. There is currently no regression meta-data.

**Closed by mfeurer** 2017-05-30 06:34 UTC
