### ISSUE TITLE
Error during installation of pyrfr

### ISSUE THREAD

**Issue by ajing** [automl/auto-sklearn#275] opened 2017-05-11 18:54 UTC
I got the following error when installing pyrfr. What is installation directory here? My current directory?

```  

(ml_env) ubuntu@ip-10-0-0-10:~/random_forest_run/build$ curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   230  100   230    0     0   2334      0 --:--:-- --:--:-- --:--:--  4893
Requirement already satisfied: unittest2 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: six>=1.4 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from unittest2)
Requirement already satisfied: argparse in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from unittest2)
Requirement already satisfied: traceback2 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from unittest2)
Requirement already satisfied: linecache2 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from traceback2->unittest2)
Requirement already satisfied: setuptools in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg
Requirement already satisfied: nose in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: six in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: Cython in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: numpy<1.12,>=1.9.0 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: scipy>=0.14.1 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: numpy>=1.8.2 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from scipy>=0.14.1)
Requirement already satisfied: scikit-learn==0.17.1 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: lockfile in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: joblib in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: psutil in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: pyyaml in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: ConfigArgParse in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: liac-arff in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: pandas in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: python-dateutil>=2 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: numpy>=1.7.0 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from python-dateutil>=2->pandas)
Requirement already satisfied: xgboost==0.4a30 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: scipy in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from xgboost==0.4a30)
Requirement already satisfied: numpy in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from xgboost==0.4a30)
Requirement already satisfied: ConfigSpace<0.4,>=0.3.1 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: typing in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.1)
Requirement already satisfied: numpy in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.1)
Requirement already satisfied: argparse in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.1)
Requirement already satisfied: pyparsing in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.1)
Requirement already satisfied: pynisher>=0.4 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: docutils>=0.3 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from pynisher>=0.4)
Requirement already satisfied: psutil in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from pynisher>=0.4)
Requirement already satisfied: setuptools in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg (from pynisher>=0.4)

Collecting pyrfr
  Using cached pyrfr-0.4.0.tar.gz
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /home/ubuntu/anaconda3/envs/ml_env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-axcsozeu/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpmdz8gclmpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pyrfr
  copying pyrfr/__init__.py -> build/lib.linux-x86_64-3.6/pyrfr
  running build_ext
  building '_regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/pyrfr
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/home/ubuntu/anaconda3/envs/ml_env/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  g++ -pthread -shared -L/home/ubuntu/anaconda3/envs/ml_env/lib -Wl,-rpath=/home/ubuntu/anaconda3/envs/ml_env/lib,--no-as-needed build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -L/home/ubuntu/anaconda3/envs/ml_env/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/_regression.cpython-36m-x86_64-linux-gnu.so
  building '_util' extension
  swigging pyrfr/util.i to pyrfr/util_wrap.cpp
  swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
  gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/home/ubuntu/anaconda3/envs/ml_env/include/python3.6m -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-3.6/pyrfr/util_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  g++ -pthread -shared -L/home/ubuntu/anaconda3/envs/ml_env/lib -Wl,-rpath=/home/ubuntu/anaconda3/envs/ml_env/lib,--no-as-needed build/temp.linux-x86_64-3.6/pyrfr/util_wrap.o -L/home/ubuntu/anaconda3/envs/ml_env/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/_util.cpython-36m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  copying build/lib.linux-x86_64-3.6/_regression.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/pyrfr
  copying build/lib.linux-x86_64-3.6/pyrfr/__init__.py -> build/bdist.linux-x86_64/wheel/pyrfr
  copying build/lib.linux-x86_64-3.6/_util.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
  running install_egg_info
  running egg_info
  writing pyrfr.egg-info/PKG-INFO
  writing dependency_links to pyrfr.egg-info/dependency_links.txt
  writing top-level names to pyrfr.egg-info/top_level.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'pyrfr.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.pxd' under directory 'pyrfr'
  warning: no files found matching '*.pyx' under directory 'pyrfr'
  warning: manifest_maker: MANIFEST.in, line 11: unknown action 'CMakeList.txt'
  
  writing manifest file 'pyrfr.egg-info/SOURCES.txt'
  Copying pyrfr.egg-info to build/bdist.linux-x86_64/wheel/pyrfr-0.4.0-py3.6.egg-info
  running install_scripts
  Checking .pth file support in build/bdist.linux-x86_64/wheel/
  /home/ubuntu/anaconda3/envs/ml_env/bin/python -E -c pass
  TEST FAILED: build/bdist.linux-x86_64/wheel/ does NOT support .pth files
  error: bad install directory or PYTHONPATH
  creating build/bdist.linux-x86_64/wheel/pyrfr
  copying build/lib.linux-x86_64-3.6/pyrfr/__init__.py -> build/bdist.linux-x86_64/wheel/pyrfr
  copying build/lib.linux-x86_64-3.6/_util.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
  running install_egg_info
  running egg_info
  writing pyrfr.egg-info/PKG-INFO
  writing dependency_links to pyrfr.egg-info/dependency_links.txt
  writing top-level names to pyrfr.egg-info/top_level.txt
  warning: manifest_maker: standard file '-c' not found 

  reading manifest file 'pyrfr.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'


      You are attempting to install a package to a directory that is not
      on PYTHONPATH and which Python does not read ".pth" files from.  The
      installation directory you specified (via --install-dir, --prefix, or
      the distutils default setting) was:
  
      build/bdist.linux-x86_64/wheel/


  and your PYTHONPATH environment variable currently contains:
  
      ''
  
  Here are some of your options for correcting the problem:
  
  * You can choose a different installation directory, i.e., one that is
    on PYTHONPATH or supports .pth files
  
  * You can add the installation directory to the PYTHONPATH environment
    variable.  (It must then also be on PYTHONPATH whenever you run
    Python and want to use the package(s) you are installing.)
  
  * You can set up the installation directory to support ".pth" files by
    using one of the approaches described here:
  
    https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
  
  
  Please make the appropriate changes for your system and try again.
  
  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr

Failed to build pyrfr
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... done
  Could not find .egg-info directory in install record for pyrfr from https://pypi.python.org/packages/21/4c/58533c51ab301f61d3521dc4cd29ba8145eed8f11b84f70aba9fd28f6aca/pyrfr-0.4.0.tar.gz#md5=70ccd2527bd85c18b8a65c7498d5e0de
Successfully installed pyrfr-0.4.0
Requirement already satisfied: smac==0.3.0 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages
Requirement already satisfied: numpy>=1.7.1 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: scipy>=0.18.1 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: scikit-learn in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: pyrfr in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: ConfigSpace>=0.3.1 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: pynisher>=0.4.1 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: psutil in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: typing in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: setuptools in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg (from smac==0.3.0)
Requirement already satisfied: Cython in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: six in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from smac==0.3.0)
Requirement already satisfied: pyparsing in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from ConfigSpace>=0.3.1->smac==0.3.0)
Requirement already satisfied: argparse in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from ConfigSpace>=0.3.1->smac==0.3.0)
Requirement already satisfied: docutils>=0.3 in /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages (from pynisher>=0.4.1->smac==0.3.0)



```

**Comment by mfeurer** [comment] 2017-05-11 18:56
Could you please post the following error? Also, does it actually fail to install the pyrfr or is it failing to build the wheel and install fine afterwards?

**Comment by ajing** [comment] 2017-05-11 18:59
Yes failing to build the wheel. But also failed to build pyrfr.

**Comment by mfeurer** [comment] 2017-05-11 19:03
Could you please paste the complete output (including your call to setup and when it returns to the shell symbol)? What you pasted so far looks fine. I'll have a look tomorrow.

**Comment by ajing** [comment] 2017-05-11 19:05
Does auto-sklearn has requirement on the version of pyrfr? Looks like it require pyrfr to be exactly 0.2.

Thanks for helping!

**Comment by mfeurer** [comment] 2017-05-12 09:23
Okay, so the installation went fine although there are two error messages. Yes, the current version of auto-sklearn requires version 0.2. Version 0.4 is a rewrite with a different interface. Hopefully I get a release of auto-sklearn together soon which uses the new random forest. Otherwise, you could install auto-sklearn from github in the meantime:

    pip install git+https://github.com/automl/auto-sklearn@development

**Comment by mfeurer** [comment] 2017-05-12 09:25
I also opened an upstream issue https://github.com/automl/random_forest_run/issues/19

**Comment by ajing** [comment] 2017-05-12 17:12
Thanks! Installing from github works!

`pip install git+https://github.com/automl/auto-sklearn@development`

**Comment by ajing** [comment] 2017-05-12 17:19
I got another error because the version of scikit-learn

```
(ml_env) ubuntu@ip-10-0-0-10:~$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:54:23) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import autosklearn.classification

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/__init__.py", line 16, in <module>
    dependencies.verify_packages(__MANDATORY_PACKAGES__)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/util/dependencies.py", line 26, in verify_packages
    _verify_package(name, operation, version)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/util/dependencies.py", line 57, in _verify_package
    required_version)
autosklearn.util.dependencies.IncorrectPackageVersionError: 'scikit-learn 0.18.1' version mismatch (==0.17.1)
```

**Comment by mfeurer** [comment] 2017-05-12 18:30
Sorry for the version chaos. This is really weird. Could you please paste the output of:

    cat /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/__init__.py
    cat /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/__version__.py

**Comment by ajing** [comment] 2017-05-12 20:18
```
(ml_env) ubuntu@ip-10-0-0-10:~$ cat /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/__init__.py
# -*- encoding: utf-8 -*-
from autosklearn.util import dependencies
from autosklearn.__version__ import __version__


__MANDATORY_PACKAGES__ = '''
numpy>=1.9,<1.12
scikit-learn==0.17.1
smac==0.3.0
lockfile>=0.10
ConfigSpace>=0.3.1,<0.4
pyrfr==0.2.0
xgboost==0.4a30
'''

dependencies.verify_packages(__MANDATORY_PACKAGES__)
(ml_env) ubuntu@ip-10-0-0-10:~$ cat /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/__version__.py 
"""Version information."""

# The following line *must* be the last in the module, exactly as formatted:
__version__ = "0.1.3"

```

**Comment by ajing** [comment] 2017-05-12 20:26
After uninstall and reinstall several times, I think I fixed it. Thanks! @mfeurer 

I have some errors during running the provided example, is this normal?

```
(ml_env) ubuntu@ip-10-0-0-10:~/Kaggle$ python
Python 3.6.1 |Continuum Analytics, Inc.| (default, Mar 22 2017, 19:54:23) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import autosklearn.classification
>>> import sklearn.cross_validation
/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
>>> import sklearn.datasets
>>> import sklearn.metrics
>>> digits = sklearn.datasets.load_digits()
>>> X = digits.data
>>> y = digits.target
>>> X_train, X_test, y_train, y_test = \
...    sklearn.cross_validation.train_test_split(X, y, random_state=1)
>>> automl = autosklearn.classification.AutoSklearnClassifier()
>>> automl.fit(X_train, y_train)
[WARNING] [2017-05-12 20:24:08,889:AutoMLSMBO(1)::c3430cb9aff96a8543a03a052e9f72db] Could not find meta-data directory /home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/metalearning/files/accuracy_multiclass.classification_dense
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
You are already timing task: index_run2
[WARNING] [2017-05-12 20:24:39,216:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2017-05-12 20:24:39,216:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
You are already timing task: index_run4

```

**Comment by ajing** [comment] 2017-05-12 21:10
Also KeyboardInterrupt notice.

```
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1547424 current, 1547424 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1547424 current, 1547424 max
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 1547424 current, 1547424 max
Process pynisher function call:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 28, in fit_predict_try_except_decorator
    return ta(queue=queue, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 312, in eval_holdout
    evaluator.fit_predict_and_loss(iterative=iterative)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 93, in fit_predict_and_loss
    i, train_indices=train_split, test_indices=test_split)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 236, in _partial_fit_and_predict
    self.Y_train[train_indices])
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 350, in _fit_and_suppress_warnings
    model.fit(X, y)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 88, in fit
    X, fit_params = self.fit_transformer(X, y, fit_params=fit_params)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/pipeline/classification.py", line 102, in fit_transformer
    X, y, fit_params=fit_params)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 98, in fit_transformer
    X, fit_params = self._fit(X, y, **fit_params)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/pipeline.py", line 236, in _fit
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/pipeline/components/base.py", line 379, in fit
    return self.choice.fit(X, y, **kwargs)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/autosklearn/pipeline/components/feature_preprocessing/kernel_pca.py", line 37, in fit
    self.preprocessor.fit(X)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/decomposition/kernel_pca.py", line 236, in fit
    K = self._get_kernel(X)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/decomposition/kernel_pca.py", line 164, in _get_kernel
    **params)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1399, in pairwise_kernels
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1083, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 801, in sigmoid_kernel
    K = safe_sparse_dot(X, Y.T, dense_output=True)
  File "/home/ubuntu/anaconda3/envs/ml_env/lib/python3.6/site-packages/sklearn/utils/extmath.py", line 189, in safe_sparse_dot
    return fast_dot(a, b)
KeyboardInterrupt
You are already timing task: index_run8
```

**Comment by mfeurer** [comment] 2017-05-15 07:29
Okay, the issue is actually related to the current release not specifying the version of the pyrfr. I hope that I'm able to release a new version today or tomorrow. Thus, I will close this issue now.

Regarding the error log. The warnings about the pthread limit should go away with:

    import sys
    sys.setrecursionlimit(40000)

The KeyboardInterrupt should not break the optimization process. In case auto-sklearn stops afterwards, please open a new issue.

**Closed by mfeurer** 2017-05-15 07:29 UTC

**Comment by micahjsmith** [comment] 2017-05-23 15:11
Hello, I'm having the same problem `pyrfr` installation failure trying to install `auto-sklearn@v.0.2.0.`  I've read through this thread several times but am still confused about how you recommend installing. The requirements.txt file on the auto-sklearn development branch still lists `pyrfr>=0.4.0` as a dependency, but I can't build `pyrfr` at all for the reasons listed above. I can, however, build `pyrfr==0.2.0`. So do you recommend installing development branch of auto-sklearn, but bypassing requirements.txt file and installing pyrfr 0.2.0? Or something else? Thanks.

**Comment by mfeurer** [comment] 2017-05-23 15:40
This issue should no longer apply as the development branch is now merged into the master branch and the version is the same as the one on pypi. I recommend using auto-sklearn 0.2.0. This version will only work with `pyrfr>=0.4.0`. Could you please paste the exact output of `pip install pyrfr==0.4.0`?

**Comment by mitar** [comment] 2017-05-28 22:34
I am getting above error "PYTHONPATH or supports .pth files" for auto-sklearn 0.2.0 as well. Not sure if I should be worried or not?

**Comment by micahjsmith** [comment] 2017-05-28 22:58
My verdict is that I am able to install successfully using auto-sklearn 0.2.0 and pyrfr 0.4.0. As others have reported, pyrfr fails trying to build the wheel but still can be used successfully. Thanks for your work.

@mfeurer

**Comment by mitar** [comment] 2017-05-28 23:19
OK, great to know that this is then just an esthetics issue. Probably really best tracked in: https://github.com/automl/random_forest_run/issues/19

**Comment by engelen** [comment] 2017-09-14 09:57
@ajing Did you by any chance find out more about the KeyboardInterrupt error? Is it causing any further problems for you, or do have a lead on how to fix it?

**Comment by ajing** [comment] 2017-09-14 16:35
@engelen I just ignore it...

**Comment by engelen** [comment] 2017-09-14 17:55
Well, that's a viable solution for most problems in life :-).
