### ISSUE TITLE
Can't import autosklearn.classification

### ISSUE THREAD

**Issue by maju3634** [automl/auto-sklearn#639] opened 2019-02-22 01:56 UTC
I am trying to import autosklearn.classification insidi virtual environment on Anaconda. But i got this result: 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-8ebeee31c13f> in <module>
      1 import numpy as np
      2 import pandas as pd
----> 3 import autosklearn.classification
      4 from xgboost import XGBClassifier
      5 from sklearn.model_selection import train_test_split

~/anaconda3/lib/python3.7/site-packages/autosklearn/classification.py in <module>
----> 1 from autosklearn.estimators import AutoSklearnClassifier

~/anaconda3/lib/python3.7/site-packages/autosklearn/estimators.py in <module>
      8 from sklearn.utils.multiclass import type_of_target
      9 
---> 10 from autosklearn.automl import AutoMLClassifier, AutoMLRegressor, BaseAutoML
     11 from autosklearn.util.backend import create, get_randomized_directory_names
     12 

~/anaconda3/lib/python3.7/site-packages/autosklearn/automl.py in <module>
      7 import warnings
      8 
----> 9 from ConfigSpace.read_and_write import pcs
     10 import numpy as np
     11 import numpy.ma as ma

~/anaconda3/lib/python3.7/site-packages/ConfigSpace/__init__.py in <module>
     33                 "Marius Lindauer", "Jorn Tuyls"]
     34 
---> 35 from ConfigSpace.configuration_space import Configuration, \
     36     ConfigurationSpace
     37 from ConfigSpace.hyperparameters import CategoricalHyperparameter, \

~/anaconda3/lib/python3.7/site-packages/ConfigSpace/configuration_space.cpython-37m-x86_64-linux-gnu.so in init ConfigSpace.configuration_space()

.eggs/Cython-0.29.5-py3.7-linux-x86_64.egg/Cython/Includes/numpy/__init__.pxd in init ConfigSpace.hyperparameters()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

So how i can fix this problem?

**Comment by C0NTRIBUTE** [comment] 2019-02-24 17:09
I have this same error fresh off install. I get the same error roughly as above, and then when I try to import again I get: 

`AttributeError: type object 'ConfigSpace.hyperparameters.Hyperparameter' has no attribute '__reduce_cython__'`

**Comment by nielsgl** [comment] 2019-02-27 08:16
Same here, importing it the first time I get the error in OP's issue, trying to import again results in the same

```
...
ConfigSpace/hyperparameters.pyx in init ConfigSpace.hyperparameters()

AttributeError: type object 'ConfigSpace.hyperparameters.Hyperparameter' has no attribute '__reduce_cython__'
```

**Comment by mfeurer** [comment] 2019-03-04 11:41
These errors do not happen during within continuous integration. Could you please provide me with an installation instruction (preferably including AnaConda and/or Docker) to reproduce this?

**Comment by nielsgl** [comment] 2019-03-04 11:45
I think it's likely an OSX issue, just found out during the weekend that it isn't officially supported :)

**Comment by mfeurer** [comment] 2019-03-04 11:55
[This issue](https://github.com/cython/cython/issues/1953) suggests that the `__reduce_cython__` missing might be due to an older cython version?

The original problem might be caused by installing Auto-sklearn with `pip install auto-sklearn` not installing the dependencies in a useful order. To avoid this you follow the [installation instructions](https://automl.github.io/auto-sklearn/master/installation.html).

**Comment by abdelkarim336** [comment] 2019-03-07 08:58
Hey everyone,
I had the same issue, just resolved by installing the appropriate versions of Cython and numpy.
You should run the following commands:

pip install numpy==1.16.0
pip install Cython==0.27.3

This worked for me. Good luck!
PS: If you're using Jupyter notebook, you might need to restart the kernel after running the commands above.

**Comment by mfeurer** [comment] 2019-03-20 08:27
Okay, I think I have some now experience the issues myself, too:

Regarding the byte size change: this can happen if you perform `pip install auto-sklearn` with `numpy>1.4.5` installed. Please downgrade numpy prior to installation of the configspace module (or the auto-sklearn module if you install ConfigSpace as a dependency) or reinstall the configspace module with `pip install ConfigSpace --no-cache --no-deps`.

Regarding the reduce cython issue. I had this when I accidentally compiled the module to the system python and tried to execute it in a conda environment afterwards. I hope that compiling Auto-sklearn/ConfigSpace with the correct environment helps here.

**Comment by mfeurer** [comment] 2020-05-18 08:41
Closing this as the issue is already one your old, appears to be resolved, and we have had two new releases since.

Please check issue #621 and/or reopen if this problem appears again.

**Closed by mfeurer** 2020-05-18 08:41 UTC

**Comment by HuangChiEn** [comment] 2022-05-04 07:14
I encounter the same Import Error. How can i solve it by downgread the version of auto-sklearn? 
Seems I can not change the other package version just for fitting auto-sklearn requirements.

Seems simply install auto-sklearn by `pip install auto-sklearn` is not the good way.

![image](https://user-images.githubusercontent.com/52521165/166636848-0c8e678f-66fe-4048-a70d-860128a3ae1f.png)

**Comment by eddiebergman** [comment] 2022-05-04 09:44
It's fixed now, there was a version conflict, `pip install auto-sklearn` is the preffered installation method.

**Comment by HuangChiEn** [comment] 2022-05-05 00:39
> auto-sklearn

Thank you very much~ the problem is solved ~
![image](https://user-images.githubusercontent.com/52521165/166848564-ece05612-50eb-4fdb-9fbc-ef9c2f5ce5af.png)
