### ISSUE TITLE
numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

### ISSUE THREAD

**Issue by Mainak431** [automl/auto-sklearn#621] opened 2019-01-22 19:08 UTC
Importing the autosklearn . classification goes into this error.

import autosklearn.classification
  File "/home/titan/Documents/autoenv/lib/python3.5/site-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier
  File "/home/titan/Documents/autoenv/lib/python3.5/site-packages/autosklearn/estimators.py", line 5, in <module>
    from autosklearn.automl import AutoMLClassifier, AutoMLRegressor
  File "/home/titan/Documents/autoenv/lib/python3.5/site-packages/autosklearn/automl.py", line 8, in <module>
    from ConfigSpace.read_and_write import pcs
  File "/home/titan/Documents/autoenv/lib/python3.5/site-packages/ConfigSpace/__init__.py", line 33, in <module>
    from ConfigSpace.configuration_space import Configuration, \
  File "ConfigSpace/configuration_space.py", line 37, in init ConfigSpace.configuration_space
  File "__init__.pxd", line 872, in init ConfigSpace.hyperparameters
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

**Comment by KEggensperger** [comment] 2019-01-24 15:51
Can you please try using numpy>=1.16.0? According to this issue this should solve the problem: https://github.com/automl/ConfigSpace/issues/107

**Comment by mfeurer** [comment] 2019-01-28 17:34
Could you please give details about your operating system, how you installed Auto-sklearn and its dependencies and how I can reproduce this issue? For the last step it would be best if you can start from a fresh virtual environment or conda environment.

**Comment by Mainak431** [comment] 2019-01-28 17:47
OS - Ubuntu 16.04

I installed using pip install and dependencies auto installed in the process.

New virtualenv was created before installing sklearn

import autosklearn.classification to regenerate the error.

**Comment by mfeurer** [comment] 2019-01-28 18:47
This is a bit tough to debug for me as I don't have an ubuntu 16.04. I assume it's an issue with the compiler. I think that the numpy wheel is build with gcc 4.X, while your OS uses gcc 5.X and the compilations of both are not compatible. I don't really know how to solve this and you have to try yourself.

There are three suggestions on how to proceed:
* Use conda/anaconda. We continuously test that this works.
* Try numpy 1.16 as this might fix the issue as mentioned by @KEggensperger
* debug further yourself

Sorry for not being able to give you a better advice.

**Comment by Mainak431** [comment] 2019-04-01 13:18
@mfeurer numpy 1.16 is not solving the issue.

**Comment by mfeurer** [comment] 2019-04-01 13:55
Could you please check my comment [here](https://github.com/automl/auto-sklearn/issues/639#issuecomment-474733243)? Maybe that helps?

**Comment by cvphelps** [comment] 2019-09-27 02:40
On Ubuntu 18.04 I had this error. Based on comments I just ran:
```
pip install --upgrade numpy==1.16.0
```
And without changing anything else it works! Thanks @KEggensperger

**Comment by hkandpal** [comment] 2020-04-12 00:23
I have Python (Version 2.7 and 3.4) and Pandas installed on 
Amazon Linux AMI release 2018.03


[ec2-user@ip ~]$ python -V
Python 2.7.16
[ec2-user@ip ~]$ python3 -V
Python 3.5.7


[ec2-user@ip ~]$ pip3 list
Package         Version
--------------- --------
awscli          1.16.105
botocore        1.12.95
colorama        0.3.9
cx-Oracle       6.4.1
Cython          0.29.16
docutils        0.14
ez-setup        0.9
jmespath        0.9.3
numexpr         2.6.6
numpy           1.15.0
pandas          0.17.0
pip             20.0.2
pyasn1          0.4.5
python-dateutil 2.7.3
pytz            2018.5
PyYAML          3.13
rsa             3.4.2
s3transfer      0.2.0
setuptools      46.1.3
six             1.11.0
SQLAlchemy      1.2.10
tables          3.4.4
urllib3         1.24.1


[ec2-user@ip ~]$ python3
Python 3.5.7 (default, Feb 10 2020, 19:00:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> include pandas as pd
  File "<stdin>", line 1
    include pandas as pd
                 ^
SyntaxError: invalid syntax
>>>

Any idea why getting this error.

**Comment by mfeurer** [comment] 2020-04-13 10:40
@hkandpal could you please describe how your post is related to this issue and Auto-sklearn?

**Comment by mfeurer** [comment] 2020-05-18 08:03
Closing this as the issue is already one your old, appears to be resolved, and we have had two new releases since.

In case there are further issues with ConfigSpace compilation, a good explanation of what can go wrong is given in this issue: https://github.com/automl/ConfigSpace/issues/141

**Closed by mfeurer** 2020-05-18 08:03 UTC

**Comment by reginalluna** [comment] 2021-03-27 12:33
@mfeurer

thank you. It solved the issue.
