### ISSUE TITLE
Autosklearn shows this error when used with Super Computer

### ISSUE THREAD

**Issue by asmgx** [automl/auto-sklearn#1418] opened 2022-03-13 06:16 UTC
## Describe the bug ##
I am using Gadi, Australia's most powerful computer.

I have my script that uses Autosklearn 

but everytime i call **automl.fit**

I get this error

**_python3: symbol lookup error: /apps/intel-ct/2021.4.0/mkl/lib/intel64/libmkl_intel_thread.so.1: undefined symbol: omp_get_num_procs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
[ERROR] [2022-03-13 16:00:45,255:Client-AutoML(1):breast_cancer] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': "<class 'pynisher.limit_function_call.AnythingException'>", 'subprocess_stdout': '', 'subprocess_stderr': '', 'exitcode': 127, 'configuration_origin': 'DUMMY'}.
  File "/home/577/am9105/.local/lib/python3.10/site-packages/autosklearn/estimators.py", line 1045, in fit
    super().fit(
  File "/home/577/am9105/.local/lib/python3.10/site-packages/autosklearn/estimators.py", line 375, in fit
    self.automl_.fit(load_models=self.load_models, **kwargs)
  File "/home/577/am9105/.local/lib/python3.10/site-packages/autosklearn/automl.py", line 2056, in fit
    return super().fit(
  File "/home/577/am9105/.local/lib/python3.10/site-packages/autosklearn/automl.py", line 808, in fit
    self.num_run += self._do_dummy_prediction(datamanager, num_run=1)
  File "/home/577/am9105/.local/lib/python3.10/site-packages/autosklearn/automl.py", line 476, in _do_dummy_prediction
    raise ValueError(
ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': "<class 'pynisher.limit_function_call.AnythingException'>", 'subprocess_stdout': '', 'subprocess_stderr': '', 'exitcode': 127, 'configuration_origin': 'DUMMY'}._**

I used the basic classification example in 

https://automl.github.io/auto-sklearn/master/examples/20_basic/example_classification.html#sphx-glr-examples-20-basic-example-classification-py

and still getting the same error

any idea how to fix that

P.S. I called the server support team but they said they cannot help with that.

I wonder if you can help me 

OS is linux and Python3

**Comment by eddiebergman** [comment] 2022-03-24 16:46
Hi @asmgx,

I'm sorry to get back to you so late. This is not an issue fully related to auto-sklearn as I think the second line of that error dump that you provided is the root cause. `undefined symbol: omp_get_num_procs`.

OMP is a low level system library used by python and many of the C-based libraries in Python, especially for numerics and multi-processing. As this is a Super computer I figure you don't have permissions to change anything about it or much methods to debug it.

Assuming this is the cause of the issue, there's multiple places it could trigger from and the reason for it could be different. For example, I googled the error and it seems that using a virtual env like anaconda/conda might even cause issue.

* https://github.com/ContinuumIO/anaconda-issues/issues/10195

I'm sorry, I wish I could help more but it's not directly an autosklearn issue and it's not a requirement we directly specify, it's something in the environment you have setup. If you find out any more information than I'd gladly help as I can :)

P.s. For future reference, it's much easier to read an error log that's been enclosed by 3 backticks which makes
```
the font look like this
```

**Comment by asmgx** [comment] 2022-03-24 21:56
Thanks, Eddie, 
but the solution you are providing assumes Anaconda is the platform.
in Gadi supercomputer we just use Python3

I found an alternative solution 

```
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'


```

but this solution use 1 thread which defeat the purpose of using high performance comuter 

I wonder if you have a better solution?

**Comment by eddiebergman** [comment] 2022-03-25 12:09
True but the root problem seems similar, in that `symbol lookup error: /apps/intel-ct/2021.4.0/mkl/lib/intel64/libmkl_intel_thread.so.1: undefined symbol: [omp_get_num_procs](url)`. Maybe you could substitute `conda update intel-openmp` with `pip install -U intel-openmp` for the virtual environment your working in?

That's not any code `auto-sklearn` directly calls and it seems more like a numeric library or sklearn specific thing. It might be worth checking out `numpy`, `dask` and `sklearn` for similar issues.

In case you're not aware, many of the power houses of python libarries that do numerics are actually just wrappers around C/C++ code which use these shared libraries (`.so` files) such as `libmkl_intel_thread.so.1` which is apparently used somewhere. It seems that this piece of C code is trying to call `omp_get_num_procs` which is from [`OpenMP`](https://www.openmp.org/), a defacto standard interface for multi-processing. If the error says it can't find the symbol `omp_get_num_procs` then my guess is that your environment on the computer can't find whatever libs are implementing the OpenMP standard. Considering it's a super computer and this is a de-facto standard, I'd be surprised if it wasn't installed. Perhaps you need to activate it somehow which is common on some shared computing resources.

To see if you have openmp on your system you can run
`cd ~; find / | grep "openmpi" > result.txt` and then look at `~/result.txt` to see where openmpi things are. You'll likely see a lot of things pop up and that's a good sign that it's installed. As for why `libmkl_intel_thread.so.1` can't find it or use it, could be multiple issues and is well beyond the scope of what help I can provide here. You should confirm your `PATH` env variable contains some paths to whatever implements `openmpi` for you. It might also help to run the command `printenv` to view all of your environment variables and understand what your system sees when things are running.

My only last piece of advice is to try running the follow commands before your python script
```bash
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export OMP_NUM_THREADS=1
printenv  # Make sure they're set
python myscript.py
```
The reasoning is that it's helped with other multi-processing issues and maybe if they're explicitly set, it might prevent the look up of the symbol `omp_get_num_procs` which causes the crash. I don't think this is likely to work though, just adding it as the last thing I could mention. 

I'm going to close this as it's not something we can control, it's to do with your environment setup on the computer and requires help from your admins. I hope I provided enough context here to get you on the right track and feel free to point them to this issue if required. Feel free to reply and continue the discussion if you really need and find something explicit to auto-sklearn but I can't help anymore that I have, apologies.

Best,
Eddie

**Closed by eddiebergman** 2022-03-25 12:09 UTC
