### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by rodolfowenceslau** [automl/auto-sklearn#856] opened 2020-05-18 02:23 UTC
Hello!
I need help.
I created a virtual machine with Ubuntu (64-bit) and 6144 MB and 2 processors.
I installed Pycharm and followed the steps and example on the installation page (https://automl.github.io/auto-sklearn/master/installation.html#windows-osx-compatibility).
When executing the sample code the error occurs in the following excerpt "automl.fit (X_train, y_train)" the message is: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV). Am I doing something wrong? Attached are some prints.

![Screenshot_19](https://user-images.githubusercontent.com/64287643/82168089-33364d80-9894-11ea-83d3-66e077c29519.png)
![Screenshot_20](https://user-images.githubusercontent.com/64287643/82168091-3598a780-9894-11ea-9eda-e35540e62879.png)

**Comment by mfeurer** [comment] 2020-05-18 07:27
Hi, thanks for the report. Could you please upload the logfile written by Auto-sklearn. It is usually stored in a directory starting with `autosklearn_tmp_` under `/tmp`.

**Comment by rodolfowenceslau** [comment] 2020-05-18 12:27
Hi, thanks for the help.
The log is attached.

[AutoML(1)_d74860caaa557f473ce23908ff7ba369.log](https://github.com/automl/auto-sklearn/files/4644065/AutoML.1._d74860caaa557f473ce23908ff7ba369.log)

**Comment by rodolfowenceslau** [comment] 2020-05-19 01:40
> Hi, thanks for the report. Could you please upload the logfile written by Auto-sklearn. It is usually stored in a directory starting with `autosklearn_tmp_` under `/tmp`.

Hi, thanks for the help.
The log is attached.

[AutoML.1._d74860caaa557f473ce23908ff7ba369.log](https://github.com/automl/auto-sklearn/files/4647778/AutoML.1._d74860caaa557f473ce23908ff7ba369.log)

**Comment by mfeurer** [comment] 2020-05-20 16:09
I must admit that I'm a bit puzzled as Auto-sklearn does not even try a single configuration. Could you please check two things:
* which SWIG version is installed
* whether you can run one of the examples from the [SMAC3 repository](https://github.com/automl/SMAC3/tree/master/examples)

**Comment by rodolfowenceslau** [comment] 2020-05-22 18:18
> I must admit that I'm a bit puzzled as Auto-sklearn does not even try a single configuration. Could you please check two things:
> 
> * which SWIG version is installed
> * whether you can run one of the examples from the [SMAC3 repository](https://github.com/automl/SMAC3/tree/master/examples)

SWIG Version 4.0.1
any example? I say because I'm new to python!

![Screenshot_27](https://user-images.githubusercontent.com/64287643/82697404-3f792c80-9c3f-11ea-9a9d-447d0d7eb2a3.png)

**Comment by mfeurer** [comment] 2020-05-25 07:33
> SWIG Version 4.0.1

Unfortunately, we don't support SWIG4. Is it possible that you install SWIG3? Just out of curiosity, what Linux and which version is this?

> any example?

Yes, any example is fine. It's just about triggering the bug without Auto-sklearn. You could for example use https://github.com/automl/SMAC3/blob/master/examples/SMAC4HPO_rosenbrock.py

**Comment by JohnsonZhouUoa** [comment] 2020-06-01 01:15
Same issue here. 

I have uninstalled SWIG4 and install SWIG3 now.
![image](https://user-images.githubusercontent.com/18080245/83367649-b5348380-a409-11ea-8753-d9650cf40ef8.png)

The only example I could run without the message "Process finished with exit code 139 (interrupt by signal 11: SIGSEGV)" is "hyperband_mlp.py".

Any clue what is causing the issue?

Thanks.

**Comment by mfeurer** [comment] 2020-06-15 08:38
Did you completely reinstall the pyrfr with `pip install pyrfr --no-cache`?

**Comment by JohnsonZhouUoa** [comment] 2020-06-17 00:11
Hi,

Should it be like this?
![image](https://user-images.githubusercontent.com/18080245/84840458-b1ecf900-b093-11ea-8d19-e3cdb806c1a4.png)

Thanks.

**Comment by mfeurer** [comment] 2020-06-17 09:25
Yes, almost. It does not re-install because the pyrfr is already installed. Could you please do
```
pip uninstall pyrfr
pip install pyrfr --no-cache
```

**Comment by gentrexha** [comment] 2020-07-14 00:59
> > SWIG Version 4.0.1
> 
> Unfortunately, we don't support SWIG4. Is it possible that you install SWIG3? Just out of curiosity, what Linux and which version is this?
> 
> > any example?
> 
> Yes, any example is fine. It's just about triggering the bug without Auto-sklearn. You could for example use https://github.com/automl/SMAC3/blob/master/examples/SMAC4HPO_rosenbrock.py

What would be a straightforward way to install swig3?

**Comment by mfeurer** [comment] 2020-08-05 07:18
> What would be a straightforward way to install swig3?

`conda install swig=3` which gives:

```
## Package Plan ##

  environment location: /home/feurerm/miniconda/3-4.5.4/envs/test

  added / updated specs: 
    - swig=3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB

The following NEW packages will be INSTALLED:

    _libgcc_mutex: 0.1-main         
    libgcc-ng:     9.1.0-hdf63c60_0 
    libstdcxx-ng:  9.1.0-hdf63c60_0 
    pcre:          8.44-he6710b0_0  
    swig:          3.0.12-h38cdd7d_3

Proceed ([y]/n)? y


Downloading and Extracting Packages
_libgcc_mutex-0.1    | 3 KB      | ############################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by relue** [comment] 2020-08-08 19:24
The problem is that in a new ubuntu swig 4 gets installed and if you install swig 3 it has an incompatible name swig3.0. Maybe its possible to resolve this dependency somehow as I think a lot of people will have trouble with this dependency.

**What worked for me:**
sudo apt-get remove swig
sudo apt install swig3.0
ln -s /usr/bin/swig3.0 /usr/bin/swig
pip uninstall pyrfr
pip install pyrfr --no-cache

**Comment by Et9797** [comment] 2021-02-07 03:04
> The problem is that in a new ubuntu swig 4 gets installed and if you install swig 3 it has an incompatible name swig3.0. Maybe its possible to resolve this dependency somehow as I think a lot of people will have trouble with this dependency.
> 
> **What worked for me:**
> sudo apt-get remove swig
> sudo apt install swig3.0
> ln -s /usr/bin/swig3.0 /usr/bin/swig
> pip uninstall pyrfr
> pip install pyrfr --no-cache

I came across the same issue and was suspecting this! Thank you! This should be added to the auto-sklaern docs until swig 4 is supported

**Comment by bikashckarmokar** [comment] 2021-03-08 12:33
thankyou 

> The problem is that in a new ubuntu swig 4 gets installed and if you install swig 3 it has an incompatible name swig3.0. Maybe its possible to resolve this dependency somehow as I think a lot of people will have trouble with this dependency.
> 
> **What worked for me:**
> sudo apt-get remove swig
> sudo apt install swig3.0
> ln -s /usr/bin/swig3.0 /usr/bin/swig
> pip uninstall pyrfr
> pip install pyrfr --no-cache

thank you. I also face this problem and the above steps solved my problem.

**Comment by mfeurer** [comment] 2021-03-08 18:45
> Maybe its possible to resolve this dependency somehow as I think a lot of people will have trouble with this dependency.

This is a non-python dependency and I am not aware of any way to handle such dependencies when installing a python package. @bastianzim is working on a conda forge installable that'll also solve this issue. Furthermore, we have just uploaded wheels to pypi to circumvent this issue (`pip installl pyrfr>=0.8.1`). I'm therefore closing this issue, please open a new issue if there's a problem with the wheels.

If there is anyone familiar with SWIG reading this issue, please have a look at https://github.com/swig/swig/issues/1955 for the underlying issue in SWIG (and please provide a fix :) )

**Closed by mfeurer** 2021-03-08 18:45 UTC
Labels: document this
