### ISSUE TITLE
`get_configuration_space()` fails

### ISSUE THREAD

**Issue by mlindauer** [automl/auto-sklearn#943] opened 2020-09-07 07:34 UTC
## Describe the bug ##
`get_configuration_space()` fails

## To Reproduce ##
`print(automl.get_configuration_space(X_train, y_train))`

## Expected behavior ##
printing the configuration space

## Actual behavior, stacktrace or logfile ##

```
Traceback (most recent call last):
[...]
    print(automl.get_configuration_space(X_train, y_train))
  File "/home/lindauer/anaconda3/envs/machining2020/lib/python3.7/site-packages/autosklearn/estimators.py", line 609, in get_configuration_space
    self._automl = self.build_automl()
TypeError: build_automl() missing 6 required positional arguments: 'seed', 'shared_mode', 'ensemble_size', 'initial_configurations_via_metalearning', 'tmp_folder', and 'output_folder'
```

**Comment by franchuterivera** [comment] 2021-02-17 23:01
This was solved! (I cannot reproduce it anymore in the latest version, so I am closing this now).

**Closed by franchuterivera** 2021-02-17 23:01 UTC
Labels: bug
