### ISSUE TITLE
auto-sklearn installation

### ISSUE THREAD

**Issue by tmielika** [automl/auto-sklearn#532] opened 2018-08-20 01:51 UTC
It would be great if step ```curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install``` would not be needed but ```pip install auto-sklearn``` would suffice.

It seems that in current setup Cython and numpy are needed for cythonizing but others can be installed as a part of pip install.

**Comment by mfeurer** [comment] 2018-09-12 15:00
Agreed, but I'm closing this for now as it is a duplicate of #519.

**Comment by mfeurer** [comment] 2021-09-10 15:03
Documented in #1237

**Closed by mfeurer** 2021-09-10 15:03 UTC
