### ISSUE TITLE
example_parallel.py does not work with the current autosklearn

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#96] opened 2016-05-09 22:24 UTC
These are repeating many times:
```
No handlers could be found for logger "multiprocessing"
Fatal Python error: Couldn't create autoTLSkey mapping
```
then this comes up also repeating itself for each process seed
```
[WARNING] [2016-05-09 15:19:54,347:AutoML(3):digits] model directory already exists
[INFO] [2016-05-09 15:19:54,351:AutoML(3):digits] Starting to create dummy predictions.
[WARNING] [2016-05-09 15:19:54,349:AutoML(2):digits] model directory already exists
[INFO] [2016-05-09 15:19:54,356:AutoML(2):digits] Starting to create dummy predictions.
[WARNING] [2016-05-09 15:19:54,370:AutoML(5):digits] model directory already exists
[INFO] [2016-05-09 15:19:54,476:AutoML(5):digits] Starting to create dummy predictions.
[ERROR] [2016-05-09 15:19:55,382:AutoML(2):digits] Error creating dummy prediction 1/2:
[ERROR] [2016-05-09 15:19:55,389:AutoML(3):digits] Error creating dummy prediction 1/2:
[ERROR] [2016-05-09 15:19:55,504:AutoML(5):digits] Error creating dummy prediction 1/2:
[ERROR] [2016-05-09 15:19:56,413:AutoML(2):digits] Error creating dummy prediction 2/2
[ERROR] [2016-05-09 15:19:56,414:AutoML(3):digits] Error creating dummy prediction 2/2
[ERROR] [2016-05-09 15:19:56,534:AutoML(5):digits] Error creating dummy prediction 2/2
[INFO] [2016-05-09 15:19:58,043:AutoML(2):digits] Start Ensemble with 56.30sec time left
[INFO] [2016-05-09 15:19:58,053:AutoML(2):digits] Start SMAC with 56.29sec time left
[ERROR] [2016-05-09 15:19:58,080:EnsembleBuilder(2):digits] Model only predicts at random: predictions_ensemble_2_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,082:EnsembleBuilder(2):digits] Model only predicts at random: predictions_ensemble_3_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,084:EnsembleBuilder(2):digits] Model only predicts at random: predictions_ensemble_4_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,086:EnsembleBuilder(2):digits] Model only predicts at random: predictions_ensemble_5_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,087:EnsembleBuilder(2):digits] Caught ValueError: Ensemble size cannot be less than one!
[INFO] [2016-05-09 15:19:58,094:AutoML(3):digits] Start Ensemble with 56.24sec time left
[INFO] [2016-05-09 15:19:58,104:AutoML(3):digits] Start SMAC with 56.24sec time left
[ERROR] [2016-05-09 15:19:58,128:EnsembleBuilder(3):digits] Model only predicts at random: predictions_ensemble_2_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,130:EnsembleBuilder(3):digits] Model only predicts at random: predictions_ensemble_3_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,141:EnsembleBuilder(3):digits] Model only predicts at random: predictions_ensemble_4_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,147:EnsembleBuilder(3):digits] Model only predicts at random: predictions_ensemble_5_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,150:EnsembleBuilder(3):digits] Caught ValueError: Ensemble size cannot be less than one!
[INFO] [2016-05-09 15:19:58,217:AutoML(5):digits] Start Ensemble with 56.14sec time left
[INFO] [2016-05-09 15:19:58,225:AutoML(5):digits] Start SMAC with 56.14sec time left
[ERROR] [2016-05-09 15:19:58,240:EnsembleBuilder(5):digits] Model only predicts at random: predictions_ensemble_2_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,243:EnsembleBuilder(5):digits] Model only predicts at random: predictions_ensemble_3_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,245:EnsembleBuilder(5):digits] Model only predicts at random: predictions_ensemble_4_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,248:EnsembleBuilder(5):digits] Model only predicts at random: predictions_ensemble_5_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:19:58,250:EnsembleBuilder(5):digits] Caught ValueError: Ensemble size cannot be less than one!
```
many more of such errors and then 

`[ERROR] [2016-05-09 15:20:55,306:EnsembleBuilder(1):digits] Model only predicts at random: predictions_ensemble_4_00001.npy has score: -0.000335683115139
[ERROR] [2016-05-09 15:20:55,308:EnsembleBuilder(1):digits] Model only predicts at random: predictions_ensemble_5_00001.npy has score: -0.000335683115139
[INFO] [2016-05-09 15:20:55,337:EnsembleBuilder(1):digits] Ensemble Selection:
        Trajectory: 0: 0.006378 1: 0.006378 2: 0.006378 3: 0.006378 4: 0.006378 5: 0.006378 6: 0.006378 7: 0.006378 8: 0.006378 9: 0.006378
        Members: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        Weights: [ 1.  0.  0.  0.]
        Identifiers: (2, 2)
[INFO] [2016-05-09 15:20:55,338:EnsembleBuilder(1):digits] Training performance: 0.006378
[INFO] [2016-05-09 15:20:55,338:EnsembleBuilder(1):digits] Building the ensemble took 0.037143 seconds
[INFO] [2016-05-09 15:20:55,339:EnsembleBuilder(1):digits] Could not find as many validation set predictions (0)as ensemble predictions (8)!.
[INFO] [2016-05-09 15:20:55,339:EnsembleBuilder(1):digits] Could not find as many test set predictions (0) as ensemble predictions (8)!
[(1.000000, MyDummyClassifier(configuration=2, random_states=None)),
]
('Accuracy score', 0.0903387703889586)
(END)
`

**Comment by Motorrat** [comment] 2016-05-10 07:18
Python 2.7.11 (as there was a bug with the same error message in 2.7.2)

**Comment by mfeurer** [comment] 2016-05-10 07:34
I have no idea where this comes from. Are any memory limits involved except the ones from auto-sklearn? Could you try this with python 3?

**Comment by Motorrat** [comment] 2016-05-10 08:41
I have dropped `import logging` and it seems to run now. However it runs for an hour and a half already, I wonder why it does that.

```
[WARNING] [2016-05-09 23:59:07,988:AutoML(4):digits] model directory already exists
[WARNING] [2016-05-09 23:59:07,997:AutoML(3):digits] model directory already exists
[INFO] [2016-05-09 23:59:08,006:AutoML(2):digits] Starting to create dummy predictions.
[INFO] [2016-05-09 23:59:08,017:AutoML(3):digits] Starting to create dummy predictions.
[INFO] [2016-05-09 23:59:08,140:AutoML(2):digits] Finished creating dummy prediction 1/2.
[INFO] [2016-05-09 23:59:08,157:AutoML(3):digits] Finished creating dummy prediction 1/2.
[INFO] [2016-05-09 23:59:08,228:AutoML(4):digits] Finished creating dummy prediction 1/2.
[INFO] [2016-05-09 23:59:08,253:AutoML(2):digits] Finished creating dummy prediction 2/2.
[INFO] [2016-05-09 23:59:08,268:AutoML(3):digits] Finished creating dummy prediction 2/2.
[INFO] [2016-05-09 23:59:08,344:AutoML(4):digits] Finished creating dummy prediction 2/2.
[INFO] [2016-05-09 23:59:09,977:AutoML(2):digits] Start Ensemble with 58.01sec time left
[INFO] [2016-05-09 23:59:09,995:AutoML(2):digits] Start SMAC with 57.99sec time left
[INFO] [2016-05-09 23:59:09,999:AutoML(3):digits] Start Ensemble with 57.99sec time left
[INFO] [2016-05-09 23:59:10,014:AutoML(3):digits] Start SMAC with 57.97sec time left
[WARNING] [2016-05-09 23:59:10,026:EnsembleBuilder(2):digits] Error loading predictions_ensemble_2_00001.npy: Solution and prediction have different number of samples: 331 and 330
[ERROR] [2016-05-09 23:59:10,026:EnsembleBuilder(2):digits] Model only predicts at random: predictions_ensemble_2_00001.npy has score: -1
[WARNING] [2016-05-09 23:59:10,027:EnsembleBuilder(2):digits] Error loading predictions_ensemble_2_00002.npy: Solution and prediction have different number of samples: 331 and 330
[ERROR] [2016-05-09 23:59:10,027:EnsembleBuilder(2):digits] Model only predicts at random: predictions_ensemble_2_00002.npy has score: -1
[INFO] [2016-05-09 23:59:10,028:AutoMLSMBO(2)::digits] Training default configurations on a subset of 330/1000 data points.
[WARNING] [2016-05-09 23:59:10,038:EnsembleBuilder(3):digits] Error loading predictions_ensemble_2_00001.npy: Solution and prediction have different number of samples: 331 and 330
[ERROR] [2016-05-09 23:59:10,038:EnsembleBuilder(3):digits] Model only predicts at random: predictions_ensemble_2_00001.npy has score: -1
[WARNING] [2016-05-09 23:59:10,039:EnsembleBuilder(3):digits] Error loading predictions_ensemble_2_00002.npy: Solution and prediction have different number of samples: 331 and 330
[ERROR] [2016-05-09 23:59:10,039:EnsembleBuilder(3):digits] Model only predicts at random: predictions_ensemble_2_00002.npy has score: -1
[INFO] [2016-05-09 23:59:10,041:AutoMLSMBO(2)::digits] Starting to evaluate 3 on SUBSET with size 330 and time limit 30s.
[INFO] [2016-05-09 23:59:10,041:AutoMLSMBO(2)::digits] Configuration:
  balancing:strategy, Value: none
  classifier:__choice__, Value: random_forest
  classifier:random_forest:bootstrap, Value: True
  classifier:random_forest:criterion, Value: gini
  classifier:random_forest:max_depth, Constant: None
  classifier:random_forest:max_features, Value: 1.0
  classifier:random_forest:max_leaf_nodes, Constant: None
  classifier:random_forest:min_samples_leaf, Value: 1
  classifier:random_forest:min_samples_split, Value: 2
  classifier:random_forest:min_weight_fraction_leaf, Constant: 0.0
  classifier:random_forest:n_estimators, Constant: 100
  imputation:strategy, Value: mean
  one_hot_encoding:minimum_fraction, Value: 0.01
  one_hot_encoding:use_minimum_fraction, Value: True
  preprocessor:__choice__, Value: no_preprocessing
  rescaling:__choice__, Value: min/max

an hour and a half later

[INFO] [2016-05-10 01:35:19,830:AutoMLSMBO(4)::digits] Finished evaluating 1323. configuration. Duration: 0.346514; loss: 0.033568; status 1; additional run info: ;duration: 0.346513986588;num_run:01323
[INFO] [2016-05-10 01:35:19,839:AutoMLSMBO(4)::digits] Starting to evaluate 1324. configuration (from SMAC) with time limit 60s.
[INFO] [2016-05-10 01:35:19,840:AutoMLSMBO(4)::digits] Configuration:
  balancing:strategy, Value: none
  classifier:__choice__, Value: gaussian_nb
  imputation:strategy, Value: mean
  one_hot_encoding:minimum_fraction, Value: 0.046333272654
  one_hot_encoding:use_minimum_fraction, Value: True
  preprocessor:__choice__, Value: pca
  preprocessor:pca:keep_variance, Value: 0.656891456911
  preprocessor:pca:whiten, Value: False
  rescaling:__choice__, Value: min/max

```

**Comment by Motorrat** [comment] 2016-05-10 08:46
And there is only one process doing some cpu work 
```
 5515 ekobylki  20   0 1788m 200m 5108 R 99.9  0.1  43:09.26 python example_parallel.py
 5442 ekobylki  20   0 1655m  82m  17m S  0.0  0.0   0:04.31 python example_parallel.py
 5489 ekobylki  20   0 1666m  78m 3588 S  0.0  0.0   0:01.95 python example_parallel.py                                                                 5513 ekobylki  20   0 1666m  76m 1272 S  0.0  0.0   0:00.00 python example_parallel.py
```

**Comment by Motorrat** [comment] 2016-05-10 11:42
I have increased the memory limit in the example from 1024 to 10240 and it got me an accuracy score 0.9x. It still prints ton of ERROR messages to the stdout. 

I have added another zero (-> 102400) and the number of errors went down but the score did not increase.

**Comment by Motorrat** [comment] 2016-05-10 12:05
and I still get these 
`  automl.fit(X_train, y_train, dataset_name=dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/automl.py", line 175, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/automl.py", line 404, in _fit
    self._load_models()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/automl.py", line 524, in _load_models
    self.models_ = self._backend.load_all_models(seed)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/util/backend.py", line 171, in load_all_models
    models = self.load_models_by_file_names(model_files)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/util/backend.py", line 185, in load_models_by_file_names
    seed = int(basename_parts[0])
ValueError: invalid literal for int() with base 10: 'tmpyRABCj'
`

**Comment by Motorrat** [comment] 2016-05-10 12:06
Increased the time limits to 360 from 60 and 150 from 15 and got to .98870 score. So it seems to be working

**Comment by Motorrat** [comment] 2016-05-10 12:20
I understand this is just a manifestation of one try failing but it still comes up as an exception

`Process pynisher function call:
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/sklearn/pipeline.py", line 147, in _pre_transform
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 33, in fit
    self.preprocessor.fit(X)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py", line 523, in fit
    self._fit(X, compute_sources=False)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py", line 479, in _fit
    compute_sources=compute_sources, return_n_iter=True)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py", line 335, in fastica
    W, n_iter = _ica_par(X1, **kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/sklearn/decomposition/fastica_.py", line 116, in _ica_par
    warnings.warn('FastICA did not converge. Consider increasing '
UserWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
`

**Comment by mfeurer** [comment] 2016-05-10 21:28
Hm, I can't reproduce the error you observe on my machine. I can only see the huge amount of errors and try to reduce them in the development branch right now. What happens if you increase the time per algorithm execution, but keeps the memory low?

**Comment by Motorrat** [comment] 2016-05-10 21:41
I will re-run and let you know. The huge number of irrelevant errors and warnings indeed makes the configuration a bit cumbersome.

**Comment by Motorrat** [comment] 2016-05-10 22:22
Increasing time from 60 to 600 and from 15 to 150 helped. 'Accuracy score', 0.9899623588456713

**Comment by mfeurer** [comment] 2016-05-11 06:12
Thanks for the information. Since I can't reproduce this and we found a solution that works for you, I'm closing this issue for now.

**Closed by mfeurer** 2016-05-11 06:12 UTC

**Comment by Motorrat** [comment] 2016-05-11 08:31
I would add this tip as a comment - # try increasing memory or time allowance x10 if the models don't converge
