### ISSUE TITLE
Error installing pyrfr

### ISSUE THREAD

**Issue by tsekulski** [automl/auto-sklearn#398] opened 2017-12-08 16:57 UTC
Hi guys,

I'm getting an error related to pyrfr when installing auto-sklearn dependencies. My environment is following:
- conda 4.3.21 (downgraded from latest version, but it didn't help)
- gcc (GCC) 4.8.5
- SWIG Version 3.0.10
- Python 3.6.3 :: Anaconda, Inc.

Error:
```
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /home/tomek/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-w4n4h_z_/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpcwticrigpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pyrfr
  copying pyrfr/__init__.py -> build/lib.linux-x86_64-3.6/pyrfr
  copying pyrfr/regression.py -> build/lib.linux-x86_64-3.6/pyrfr
  copying pyrfr/docstrings.i -> build/lib.linux-x86_64-3.6/pyrfr
  running build_ext
  building '_regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/pyrfr
  gcc -pthread -B /home/tomek/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./include -I/home/tomek/anaconda3/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  g++ -pthread -shared -B /home/tomek/anaconda3/compiler_compat -L/home/tomek/anaconda3/lib -Wl,-rpath=/home/tomek/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -L/home/tomek/anaconda3/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/_regression.cpython-36m-x86_64-linux-gnu.so
  /home/tomek/anaconda3/compiler_compat/ld: cannot find -lm
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: sphinx-rtd-theme, pyrfr, smac
  Running setup.py install for pyrfr ... error
    Complete output from command /home/tomek/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-w4n4h_z_/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-87xd7x77-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/pyrfr
    gcc -pthread -B /home/tomek/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./include -I/home/tomek/anaconda3/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    creating build/lib.linux-x86_64-3.6
    g++ -pthread -shared -B /home/tomek/anaconda3/compiler_compat -L/home/tomek/anaconda3/lib -Wl,-rpath=/home/tomek/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -L/home/tomek/anaconda3/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/_regression.cpython-36m-x86_64-linux-gnu.so
    /home/tomek/anaconda3/compiler_compat/ld: cannot find -lm
    collect2: error: ld returned 1 exit status
    error: command 'g++' failed with exit status 1

    ----------------------------------------
Command "/home/tomek/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-w4n4h_z_/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-87xd7x77-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-w4n4h_z_/pyrfr/
```

**Comment by tsekulski** [comment] 2017-12-08 18:49
Update:
After running `conda uninstall gcc` I have been able to install pyrfr, albeit not perfectly - see the log below. Any hint what could be going on here would be appreciated.

I suspect it might be related to the following - but I'm not an expert on compilers:
https://github.com/conda/conda/issues/6132

```
curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   206  100   206    0     0    206      0  0:00:01 --:--:--  0:00:01   673
Requirement already satisfied: setuptools in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: nose in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: six in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: Cython in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: numpy>=1.9.0 in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: scipy>=0.14.1 in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: scikit-learn<0.19,>=0.18.1 in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: lockfile in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: joblib in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: psutil in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: pyyaml in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: liac-arff in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: pandas in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: python-dateutil>=2 in /home/tomek/anaconda3/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in /home/tomek/anaconda3/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: numpy>=1.7.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from pandas)
Requirement already satisfied: six>=1.5 in /home/tomek/anaconda3/lib/python3.6/site-packages (from python-dateutil>=2->pandas)
Requirement already satisfied: ConfigSpace<0.4,>=0.3.3 in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: argparse in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.3)
Requirement already satisfied: pyparsing in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.3)
Requirement already satisfied: numpy in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.3)
Requirement already satisfied: typing in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.3)
Requirement already satisfied: pynisher>=0.4 in /home/tomek/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: psutil in /home/tomek/anaconda3/lib/python3.6/site-packages (from pynisher>=0.4)
Requirement already satisfied: setuptools in /home/tomek/anaconda3/lib/python3.6/site-packages (from pynisher>=0.4)
Requirement already satisfied: docutils>=0.3 in /home/tomek/anaconda3/lib/python3.6/site-packages (from pynisher>=0.4)
Collecting pyrfr<0.7,>=0.6.1
  Using cached pyrfr-0.6.1.tar.gz
Building wheels for collected packages: pyrfr
  Running setup.py bdist_wheel for pyrfr ... error
  Complete output from command /home/tomek/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5m4b6eoi/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpugnsbog8pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pyrfr
  copying pyrfr/__init__.py -> build/lib.linux-x86_64-3.6/pyrfr
  copying pyrfr/docstrings.i -> build/lib.linux-x86_64-3.6/pyrfr
  running build_ext
  building '_regression' extension
  swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/pyrfr
  gcc -pthread -B /home/tomek/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./include -I/home/tomek/anaconda3/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  g++ -pthread -shared -B /home/tomek/anaconda3/compiler_compat -L/home/tomek/anaconda3/lib -Wl,-rpath=/home/tomek/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -L/home/tomek/anaconda3/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/_regression.cpython-36m-x86_64-linux-gnu.so
  building '_util' extension
  swigging pyrfr/util.i to pyrfr/util_wrap.cpp
  swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
  gcc -pthread -B /home/tomek/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./include -I/home/tomek/anaconda3/include/python3.6m -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-3.6/pyrfr/util_wrap.o -O2 -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  g++ -pthread -shared -B /home/tomek/anaconda3/compiler_compat -L/home/tomek/anaconda3/lib -Wl,-rpath=/home/tomek/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.6/pyrfr/util_wrap.o -L/home/tomek/anaconda3/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/_util.cpython-36m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  copying build/lib.linux-x86_64-3.6/_regression.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
  copying build/lib.linux-x86_64-3.6/_util.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/pyrfr
  copying build/lib.linux-x86_64-3.6/pyrfr/__init__.py -> build/bdist.linux-x86_64/wheel/pyrfr
  copying build/lib.linux-x86_64-3.6/pyrfr/docstrings.i -> build/bdist.linux-x86_64/wheel/pyrfr
  running install_egg_info
  running egg_info
  writing pyrfr.egg-info/PKG-INFO
  writing dependency_links to pyrfr.egg-info/dependency_links.txt
  writing top-level names to pyrfr.egg-info/top_level.txt
  reading manifest file 'pyrfr.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pyrfr.egg-info/SOURCES.txt'
  Copying pyrfr.egg-info to build/bdist.linux-x86_64/wheel/pyrfr-0.6.1-py3.6.egg-info
  running install_scripts
  Checking .pth file support in build/bdist.linux-x86_64/wheel/
  /home/tomek/anaconda3/bin/python -E -c pass
  TEST FAILED: build/bdist.linux-x86_64/wheel/ does NOT support .pth files
  error: bad install directory or PYTHONPATH

  You are attempting to install a package to a directory that is not
  on PYTHONPATH and which Python does not read ".pth" files from.  The
  installation directory you specified (via --install-dir, --prefix, or
  the distutils default setting) was:

      build/bdist.linux-x86_64/wheel/

  and your PYTHONPATH environment variable currently contains:

      ''

  Here are some of your options for correcting the problem:

  * You can choose a different installation directory, i.e., one that is
    on PYTHONPATH or supports .pth files

  * You can add the installation directory to the PYTHONPATH environment
    variable.  (It must then also be on PYTHONPATH whenever you run
    Python and want to use the package(s) you are installing.)

  * You can set up the installation directory to support ".pth" files by
    using one of the approaches described here:

    https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


  Please make the appropriate changes for your system and try again.

  ----------------------------------------
  Failed building wheel for pyrfr
  Running setup.py clean for pyrfr
Failed to build pyrfr
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... done
  Could not find .egg-info directory in install record for pyrfr<0.7,>=0.6.1 from https://pypi.python.org/packages/5e/c0/7f1487b665f04d90b7ed69d212a4f58b74b39bd4568f2dda3a06a783dd12/pyrfr-0.6.1.tar.gz#md5=7e9969286e4d26a1680f3235a19617c7
Successfully installed pyrfr-0.6.1
Collecting smac<0.7,>=0.6.0
Requirement already satisfied: numpy>=1.7.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: scikit-learn>=0.18.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: pyrfr>=0.5.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: sphinx-rtd-theme in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: scipy>=0.18.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: setuptools in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: ConfigSpace>=0.3.8 in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: sphinx in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: typing in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: six in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: psutil in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: pynisher>=0.4.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0)
Requirement already satisfied: argparse in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace>=0.3.8->smac<0.7,>=0.6.0)
Requirement already satisfied: pyparsing in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace>=0.3.8->smac<0.7,>=0.6.0)
Requirement already satisfied: Jinja2>=2.3 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: Pygments>=2.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: docutils>=0.11 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: snowballstemmer>=1.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: imagesize in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: requests>=2.0.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: sphinxcontrib-websupport in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/tomek/anaconda3/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: pytz>=0a in /home/tomek/anaconda3/lib/python3.6/site-packages (from babel!=2.0,>=1.3->sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: idna<2.7,>=2.5 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0)
Installing collected packages: smac
Successfully installed smac-0.6.0
```

**Comment by tsekulski** [comment] 2017-12-08 18:51
P.S. auto-sklearn installation proceeded w/o any visible issues:

```
pip install auto-sklearn
Collecting auto-sklearn
  Downloading auto-sklearn-0.2.1.tar.gz (3.7MB)
    100% |████████████████████████████████| 3.7MB 354kB/s
Requirement already satisfied: setuptools in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: nose in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: six in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: Cython in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: numpy>=1.9.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: scipy>=0.14.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: scikit-learn<0.19.0,>=0.18.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: lockfile in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: joblib in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: psutil in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: pyyaml in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: liac-arff in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: pandas in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: ConfigSpace<0.4,>=0.3.3 in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: pynisher<0.5,>=0.4 in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: pyrfr<0.7,>=0.6.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: smac<0.7,>=0.6.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from auto-sklearn)
Requirement already satisfied: python-dateutil>=2 in /home/tomek/anaconda3/lib/python3.6/site-packages (from pandas->auto-sklearn)
Requirement already satisfied: pytz>=2011k in /home/tomek/anaconda3/lib/python3.6/site-packages (from pandas->auto-sklearn)
Requirement already satisfied: argparse in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.3->auto-sklearn)
Requirement already satisfied: pyparsing in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.3->auto-sklearn)
Requirement already satisfied: typing in /home/tomek/anaconda3/lib/python3.6/site-packages (from ConfigSpace<0.4,>=0.3.3->auto-sklearn)
Requirement already satisfied: docutils>=0.3 in /home/tomek/anaconda3/lib/python3.6/site-packages (from pynisher<0.5,>=0.4->auto-sklearn)
Requirement already satisfied: sphinx-rtd-theme in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: sphinx in /home/tomek/anaconda3/lib/python3.6/site-packages (from smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: Jinja2>=2.3 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: Pygments>=2.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: snowballstemmer>=1.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: imagesize in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: requests>=2.0.0 in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: sphinxcontrib-websupport in /home/tomek/anaconda3/lib/python3.6/site-packages (from sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: MarkupSafe>=0.23 in /home/tomek/anaconda3/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: idna<2.7,>=2.5 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Requirement already satisfied: certifi>=2017.4.17 in /home/tomek/anaconda3/lib/python3.6/site-packages (from requests>=2.0.0->sphinx->smac<0.7,>=0.6.0->auto-sklearn)
Building wheels for collected packages: auto-sklearn
  Running setup.py bdist_wheel for auto-sklearn ... done
  Stored in directory: /home/tomek/.cache/pip/wheels/f8/b1/d0/6af5454409ea1506e6d7604d3e0d5cf4fb291fb5ebe3ef91b3
Successfully built auto-sklearn
Installing collected packages: auto-sklearn
Successfully installed auto-sklearn-0.2.1
```

**Comment by mfeurer** [comment] 2017-12-11 12:28
Great to hear that you solved the issue! Indeed, the issue is related to recent changes in the compiler setup of Anaconda - and the current installation instructions are out of date. I hope to finally get a new release out soon with an updated installation instruction. The RF issue is known, but we don't really know how to solve it - it'll still work.

**Comment by FontTian** [comment] 2017-12-14 02:20
After I update the class library, my main work environment also encounter this problem after I use anconda created a new environment (python = 3.5) and separately installed AutoSklean to solve the problem. But I had a test, update again after class library, can't be used again. Now I have not understood exactly what caused the problem, but create a virtual environment and installation autosklearn alone alone is feasible scheme.

**Comment by mfeurer** [comment] 2018-01-05 08:52
New release is out - closing this issue.

**Closed by mfeurer** 2018-01-05 08:52 UTC
