### ISSUE TITLE
[ERROR] asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by xmyhhh** [automl/auto-sklearn#1532] opened 2022-06-27 06:19 UTC
The program throws an error at runtime, how can this error be solved?
```python
[ERROR] [2022-06-27 14:13:51,391:asyncio.events] 
Traceback (most recent call last):
  File "/home/xumaoyuan/.virtualenvs/lib/python3.8/site-packages/distributed/utils.py", line 761, in wrapper
    return await func(*args, **kwargs)
  File "/home/xumaoyuan/.virtualenvs/lib/python3.8/site-packages/distributed/client.py", line 1400, in _handle_report
    await self._reconnect()
  File "/home/xumaoyuan/.virtualenvs/lib/python3.8/site-packages/distributed/utils.py", line 761, in wrapper
    return await func(*args, **kwargs)
  File "/home/xumaoyuan/.virtualenvs/lib/python3.8/site-packages/distributed/client.py", line 1211, in _reconnect
    await self._ensure_connected(timeout=timeout)
  File "/home/xumaoyuan/.virtualenvs/lib/python3.8/site-packages/distributed/client.py", line 1241, in _ensure_connected
    comm = await connect(
  File "/home/xumaoyuan/.virtualenvs/lib/python3.8/site-packages/distributed/comm/core.py", line 313, in connect
    await asyncio.sleep(backoff)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 659, in sleep
    return await future
asyncio.exceptions.CancelledError
```

**Comment by eddiebergman** [comment] 2022-06-27 06:24
Hi @xmyhhh,

It would be helpful if you could provide more context:
* What system are you running on?
* Do you have some sample code that reproduces this?
* What version of autosklearn are you using?
* Can you provide the contents of `pip list` in your virtual env?

Best,
Eddie

**Comment by eddiebergman** [comment] 2022-06-27 08:13
Hi @xmyhhh,

I did some experimenting and the fix is `pip install distributed==2020.04`.

Not sure why the newest dask versions break things but that's a fix I have for you right now

**Comment by eddiebergman** [comment] 2022-06-27 08:56
Did some more thinking as to why this wasn't an issue. I used this [example](https://automl.github.io/auto-sklearn/master/examples/60_search/example_parallel_n_jobs.html#sphx-glr-examples-60-search-example-parallel-n-jobs-py) as a test and I'm surprised this didn't trigger for any of the tests, needs to be investigated a little further

**Comment by eddiebergman** [comment] 2022-06-27 09:39
I'll hot patch this later today :)

**Comment by eddiebergman** [comment] 2022-06-27 17:03
No longer going to hotpatch this, I thought this was a breaking issue in which autosklearn no longer function but instead it's just seems to be an error with logging within dask while we close down the dask `Client`. I'll keep a running log here as I debug it.

**Comment by eddiebergman** [comment] 2022-06-28 10:07
First thing to note is that `asyncio.exceptions.CancelledError` is absolutely fine and all of this comes from within Dask and not from us. We may be shutting down slightly incorrectly for our setup that leads to this error leak. However the errors are not harmful and exist only in the logger. `CancelledError` is basically when something tries to get a result from an async task that was cancelled (I think) and that's alright while we're shutting down anyways.

Can confirm that it happens when we try to `close()` the dask client.
https://github.com/automl/auto-sklearn/blob/4f691a1db90f47a9118c193b52bccb797b604a64/autosklearn/automl.py#L378-L379

* `shutdown()` closes down the scheduler that the `Client` is attached to first, and this closes without issue.
* `close()` will then close down the client at which point it catches this error twice from a decorator `@log_errors` and logs it.

---
At first I thought it might be reference issue where the scheduler gets collected too early since it has no named reference outside of `Client` so I moved the scheduler `LocalCluster` out of the `Client` into `self._cluster` but the issue still remained.

https://github.com/automl/auto-sklearn/blob/4f691a1db90f47a9118c193b52bccb797b604a64/autosklearn/automl.py#L355-L372

Might be worth closing down the scheduler using `self._cluster.close()` and then `self._client.close()` but I don't think this is the issue.
---
Quick check also confirmed there are no pending futures before the `shutdown()` is called so whatever was cancelled happened before we reached `dask.close()`
---
Tried to naively just use `contextlib.supress(CancelledError)` around `client.close()` but unfortunately it's just sent straight to the logger and not actually raised
---
Doesn't seem to be anything on dask about this coming up.
---
### Next suggestions

Main thing would be to identify the futures which give the CancelledError. It would also be good to create a minimal example of the above creation of the dask client, submit a job or two and then do our shutdown process and see if the problem is minimally reporducible.

1. Do we stop the client's current jobs anywhere else? These stopped jobs may need to also be removed from some internal queue of dask.
2. Can we manually trigger these errors and collect these futures outside of `close` and just catch them so dask doesn't log it?
3. Failing all that, we can just add something to our default `logging.yaml` that ignores them

**Comment by xmyhhh** [comment] 2022-06-28 13:43
I can't believe you replied so much, thanks so much but I need a moment to check your reply~

**Comment by eddiebergman** [comment] 2022-07-08 11:15
So I got back to this and created a minimal example that solves the issue. Essentially `client.shutdown()` should be reserved for usage when the Client creates the cluster itself. I created a minimal reproducible example where the issue occurs and how to solve it.

```python
# Recreate broken
from dask.distributed import Client, LocalCluster

class A:
    def do(self):
        print("setup", flush=True)
        self.client = Client(LocalCluster(n_workers=2, processes=False))
        print(f"post creation | self.client.status = {self.client.status}", flush=True)
        self.client.shutdown()
        print(f"post shutdown | self.client.status = {self.client.status}", flush=True)

a = A()
a.do()
```

```python
# Fixed
from dask.distributed import Client, LocalCluster

class A:
    def do(self):
        print("setup", flush=True)
        self.cluster = LocalCluster(n_workers=2, processes=False)
        self.client = Client(self.cluster)
        print(f"post creation | self.client.status = {self.client.status}", flush=True)
        print(f"post creation | self.cluster.status = {self.cluster.status}", flush=True)
        self.client.close()
        self.cluster.close()
        print(f"post shutdown | self.client.status = {self.client.status}", flush=True)
        print(f"post shutdown | self.cluster.status = {self.cluster.status}", flush=True)

a = A()
a.do()
```

**Closed** 2022-07-16 18:36 UTC
Labels: bug, Good first issue
