### ISSUE TITLE
backend load_ensemble - selecting the indices_files

### ISSUE THREAD

**Issue by jianswang** [automl/auto-sklearn#625] opened 2019-01-25 03:59 UTC
if seed >= 0:
            indices_files = glob.glob(os.path.join(ensemble_dir,
                                                   '%s.*.ensemble' % seed))
            indices_files.sort()

- This method sorts the indices_files starting with string of '1' . Assuming there are 12 ensembles, indices_files will be transformed to '1','10','11','12','2','3','4','5','6','7','8','9'. So the best algorithm after 9 will not be read.

with open(indices_files[-1], 'rb') as fh:
            ensemble_members_run_numbers = pickle.load(fh)
- Why do we pick the last indices_files to be read? what if the best indices_files is in between?

**Comment by mfeurer** [comment] 2019-01-28 17:38
Thanks for reporting this, but this is a duplicate of #566 and fixed via #567.

**Closed by mfeurer** 2019-01-28 17:38 UTC
