### ISSUE TITLE
Create pipeline test superclass to remove lots of redundant code

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#266] opened 2017-04-26 12:17 UTC
In addition to the checks it currently does, it should also check that the pipeline component is actually idempotent to avoid issues like #263/#260. The superclass would read the expected outcomes from a dictionary per class.

**Comment by mfeurer** [comment] 2017-06-20 07:45
Also, this should also check output matrix sizes. Partially fixed in #309.

**Comment by franchuterivera** [comment] 2020-08-05 00:40
the first question here is what test methods are redundant?

The only ones that are completely redundant are:
* test_find_preprocessors
* test_default_configuration_iterative_fit

There are methods that seem redundant,  but that can trigger/catch different outcomes. For instance, pipeline clonability might catch a broken regression component whereas the classification pipeline might be correct (and similar case with the other methods in this list). In order words, I do see the benefit of keeping the following methods separated to increase the coverage:
* test_configurations
* test_configurations_signed_data
* test_configurations_sparse
* test_get_hyperparameter_search_space
* test_pipeline_clonability
* test_get_hyperparameter_search_space_dataset_properties

Then, the following checks are pipeline specific:
* handles_regression needs separated check
* There are separated outputs like multilabel for classification and multi-output for regression
* Some of the test that could be merged, use different configurations which means, they increase the coverage a bit.
* test_predict_proba_batched only makes sense in classification

Due to this third category, it is a fact that we need classification/regression specific tests. I only found really 2 methods that are common, and unnecessarily called twice. Adding a third file/test (superset) will not remove a lot of code so I will close this until more checks are added that justify this superset.

**Closed by franchuterivera** 2020-08-05 00:40 UTC
