### ISSUE TITLE
How to get an explicit expression for an ensemble model, such as the coefficients of a regression ensemble model

### ISSUE THREAD

**Issue by belzheng** [automl/auto-sklearn#1544] opened 2022-07-21 10:00 UTC
# Short Question Description
Hi, I would like to know if I use auto-sklearn for regression, like specifying that the regressor is random forest, I know that I can get the weights and models of the ensemble model by get_models_with_weights(), show_models().My question is whether I can get the regression coefficients of the final ensemble model by calling some APIs, if not, can users write their own code to get the coefficients or display expressions of the ensemble model?

**Comment by eddiebergman** [comment] 2022-07-21 14:58
Hi @belzheng,

So the `get_models_with_weights()` will give you the ensemble weights for each model included in the ensemble. From here, you can query the model's returned from this dictionary to get further information for that specific model. I'm not really sure what you mean by "regression coefficients of the final ensemble model" in this case.

The way the ensemble works for regression is we do a simple weighted sum over the regression outputs of each model to get a final output. In the case of classification, these are done with the probabilities before being turned to classes.

If you have some sample code of what you would like to be able to do, that would help in me understanding the question some more and can help influence further design :) Thanks for reaching out!

Best,
Eddie

**Comment by belzheng** [comment] 2022-07-21 16:21
Ok, thanks, let me explain the problem in another way, here is a sample code to illustrate the question:
![1](https://user-images.githubusercontent.com/91657801/180263607-fbb22306-91ac-43e6-a99b-2590a05c1625.PNG)
![2](https://user-images.githubusercontent.com/91657801/180264147-004bf517-1026-4a12-b088-bec724711c12.PNG)
![3](https://user-images.githubusercontent.com/91657801/180264237-ffe894df-f075-49ca-af91-381ef72d6224.PNG)

So,my question is how can I get the specific coefficents in the ensemble model?

**Comment by eddiebergman** [comment] 2022-07-27 20:06
Hi @belzheng,

Sorry for the lack of response, conferences have been taking up our time :)

So autosklearn doesn't have `coefs_`. A simple model may have some simple learned parameters which are often exported as `coefs_` but not every model will have that, take for example a [KNNRegressir](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html#sklearn.neighbors.KNeighborsRegressor).

Autosklearn will train a large number of different scikit learn models and then produce an ensemble of them, as seen in `models_with_weights()`. Most of these will probably no have any `coefs_`.

A good way to illustrate the problem is if we're to have a `coefs_` attribute like the regressor does, what would we put in there? There's no meaningful answer that we can come up with that makes sense.

If you were to share your use case, I could perhaps point you in the right direction but I feel there may be some misunderstanding of what autosklearn does.

Best,
Eddie

**Comment by belzheng** [comment] 2022-07-31 14:34
Thank you very much！So my new question is, since there are no coefficients here, how do we make predictions for the regression？

**Comment by eddiebergman** [comment] 2022-08-03 08:38
You do not need coefficients for the task of regression, which is to estimate continuous numerical values from the data. You could create a model which always returns the mean of the training data and this is a perfectly valid model that has no `coef_` but is technically a valid regression model.

The coefficients you mention are part of the [LinearRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html?highlight=linearre#sklearn.linear_model.LinearRegression) model as well as some others, generally "linear" models. There is a whole variety of other models that doesn't have these `coefs_` in sklearn, for example a [`DecisionTree`](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor). It can do regression without `coefs_` but it has other parameters like `tree_` that are learned from the data.

This question is no longer really concerned with auto-sklearn and so I will close the issue. I advise exploring the scikit learn documentation some more and find some "non-linear" models and investigate how they perform regression.

Best,
Eddie

**Closed by eddiebergman** 2022-08-03 08:38 UTC
Labels: question

**Comment by mfeurer** [comment] 2022-08-03 17:05
Hey, I think there was some talking past each other. Weights in a linear model are sometimes called "coefficients" and scikit-learn appears to have the convention of giving them the name `coefs_`. EnsembleSelection is a linear model, so one could assume that there's a variable called `coefs_`. However, we don't follow this convention here, and instead assign the weights to a variable called `weights_`. I'm wondering whether we should change the variable name or simply add a second variable `coefs_` for compatibility?

**Comment by eddiebergman** [comment] 2022-08-04 08:57
That's a good point I didn't consider but I think this would then raise quite a few questions as to what `coefs_` means from autosklearn. I could see someone finding `automl.coefs_` and then wondering what those are and what they mean. This would lead to the term `weights_` and `coefs_` both floating around.

I had a brief look at all the [ensembles in sklearn](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.ensemble) as well as their [general machine learning guide on ensembles](https://scikit-learn.org/stable/modules/ensemble.html#ensemble-methods) and found no reference to `coefs_`, my guess is that it is reserved for individual models who use the coefficients directly, and not as weights to other models.

**Comment by mfeurer** [comment] 2022-08-04 09:08
Good points regarding the ensembles - we're somewhat a voting classifier, and that doesn't have `coefs_`, too. Therefore, I think we can leave things as they are.

**Comment by belzheng** [comment] 2022-08-17 15:49
Thanks for your reply,and I'm Sorry for taking so long to reply. What I want to ask is if the lasso regression in sklearn is added to the regressor of autosklearn, so that the feature preprocessing of autosklearn can be used, but I don't know how to extract the coefficients of this linear model, just like sklearn can display the model coefficients. When I tried to extract the coefficients after feature transformation by myself, I found that the ''coef_'' attribute of lasso disappeared. Below is the sample code for you to understand my problem better. thanks
![1](https://user-images.githubusercontent.com/91657801/185184635-571ea7e0-efdb-4b6d-9c1c-8987973d3716.PNG)
![2](https://user-images.githubusercontent.com/91657801/185184708-fa70a591-29fe-4a67-9fe0-8887909aa52c.PNG)
![3](https://user-images.githubusercontent.com/91657801/185184731-716a533c-b26d-40e3-8467-415e973d24ed.PNG)
![4](https://user-images.githubusercontent.com/91657801/185184756-1552f76d-438a-4cd9-a9b9-43ba79dc889a.PNG)
![5](https://user-images.githubusercontent.com/91657801/185184781-3a22af9c-b554-4f77-8c61-301f59e9daf6.PNG)
![6](https://user-images.githubusercontent.com/91657801/185184810-f2c2c90b-7b75-4110-b944-ab243174a077.PNG)
![7](https://user-images.githubusercontent.com/91657801/185184834-dd41ad1a-bbdf-411c-9b0e-989bc1445352.PNG)
![8](https://user-images.githubusercontent.com/91657801/185184847-8a55a612-228d-4766-8b6e-27830c153166.PNG)
!

**Comment by eddiebergman** [comment] 2022-08-18 08:28
Hi @belzheng,

Thanks for the more descriptive answer, you should get the underlying estimator you wrap in you `LassoRegression` class.

```python
stepauto = regpip1.steps
regressor = stepauto[-1][1]
regressor.coef_  # Error
regressor.estimator.coef_  # Should be here.
```

You don't need to refit this pipeline, you could also just get it directly from `show_models()`, the main issue was you are trying to access the `coef_` and the wrapped `estimator` and you need to access the underlying `estimator` to get all the sklearn parameters.

I hope this solves your problem?

Best,
Eddie

**Comment by belzheng** [comment] 2022-08-25 11:35
Thanks, this did solve the problem of coefficient extraction! But the next problem is that I don't konw what these transformed variables represent,and I want to know  if there is any way to know the specific form of the variables?The ultimate purpose of doing this is to use autosklearn's automatic feature processing to find nonlinear effects between variables, but it is meaningless to only know the coefficients without knowing what the variables corresponding to the coefficients are.The following code is my attempt, I can only extract the transformed `X_test`, but I have been struggling to solve its specific variable form, so I want to ask if there is a solution?
![1](https://user-images.githubusercontent.com/91657801/186653631-5fd76c48-ec33-4c2c-94a4-62ab7ce58705.PNG)
![2](https://user-images.githubusercontent.com/91657801/186653658-1df56ae1-da85-424f-886e-3369bf076786.PNG)
![3](https://user-images.githubusercontent.com/91657801/186653818-4a2562c0-e060-4ce3-a70d-db8ddf76fe26.PNG)
![4](https://user-images.githubusercontent.com/91657801/186653836-07c06443-557e-48f6-9215-885bffc4a55a.PNG)
![5](https://user-images.githubusercontent.com/91657801/186653857-dbc9cf94-b701-4fa8-bfa4-460364c02ae1.PNG)
![6](https://user-images.githubusercontent.com/91657801/186653874-929e4ba3-5455-4716-ac43-679a1338ba97.PNG)
![7](https://user-images.githubusercontent.com/91657801/186653887-a301b9f8-d9ab-48f5-a73b-8948434a8f96.PNG)
![8](https://user-images.githubusercontent.com/91657801/186653907-ee7d1113-123b-4590-be2b-8ec1414f6272.PNG)
