### ISSUE TITLE
TypeError when refit

### ISSUE THREAD

**Issue by ybee05** [automl/auto-sklearn#386] opened 2017-11-09 05:59 UTC
File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 50, in refit
    return self._automl.refit(X, y)
  File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 50, in refit
    return self._automl.refit(X, y)
  File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/automl.py", line 497, in refit
    model.fit(X.copy(), y.copy())
  File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/base.py", line 89, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/base.py", line 104, in fit_estimator
    self.steps[-1][-1].fit(X, y, **fit_params)
  File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/base.py", line 379, in fit
    return self.choice.fit(X, y, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/classification/gradient_boosting.py", line 36, in fit
    refit=True)
  File "/usr/local/lib/python3.5/dist-packages/auto_sklearn-0.2.1-py3.5-linux-x86_64.egg/autosklearn/pipeline/components/classification/gradient_boosting.py", line 68, in iterative_fit
    self.max_leaf_nodes = int(self.max_leaf_nodes)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by mfeurer** [comment] 2017-11-10 20:40
This is a duplicate of #326 and will be fixed in the upcoming release, hopefully next week.

**Closed by mfeurer** 2017-11-10 20:40 UTC
