### ISSUE TITLE
Random Forest n_estimators parameter is fixed

### ISSUE THREAD

**Issue by engelen** [automl/auto-sklearn#389] opened 2017-11-15 13:11 UTC
The number of estimators in the Random Forest classifier is set to be constant (at 100). Is there any reason not to change this to a relatively broad range, from, say, 2 to 10000?

**Comment by mfeurer** [comment] 2017-11-15 17:21
This is a duplicate of #326. The reason why we keep it fixed is because it does not have any direct interaction with any other hyperparameter (which is different in boosting) and usually adding more trees is a good idea. Because of this monotonicity in the hyperparameter space, it makes it quite hard to tune the hyperparameter because you could end up wasting a lot of time building very deep trees if you do not have a way of dynamically adding more trees to an ensemble instead of training a new configuration.

If you do know a solution to this problem it would be great to hear. All in all, the n_estimators hyperparameter for all tree-based models could be vastly improved, but doing that in a principled way seems to be a hard problem.

**Comment by mfeurer** [comment] 2020-11-03 19:14
Finally closing this as it is a duplicate.

**Closed by mfeurer** 2020-11-03 19:14 UTC
