### ISSUE TITLE
Installation problem with latest version of scikit-learn

### ISSUE THREAD

**Issue by parunach** [automl/auto-sklearn#227] opened 2017-01-22 23:45 UTC
I see that auto-sklearn requires an exact version for scikit-learn 0.17.1. The package must be able to handle later versions of scikit-learn (current version is 0.18.1). The exact version match prevents other packages from being installed.

**autosklearn.util.dependencies.IncorrectPackageVersionError: 'scikit-learn 0.18.1' version mismatch (==0.17.1)**

**Comment by mfeurer** [comment] 2017-01-23 08:32
We are aware of this issue and are working on it. I'm closing this since it's a duplicate of #186.

**Closed by mfeurer** 2017-01-23 08:32 UTC
